#!/usr/bin/env python3
"""Deterministic tooling for a project-local knowledge compilation layer.

Ships with the agent-collab plugin's `project-knowledge` skill. The layer is
a `knowledge/` directory inside the USER'S project:

    knowledge/
      sources/registry.yaml   source provenance registry (provenance is DATA,
                              never authorization)
      pages/                  compiled knowledge pages (markdown + frontmatter)
      proposals/              draft skeletons written by `draft` (untrusted;
                              promoted into pages/ only through your own
                              review process)
      index.md / log.md       generated by `index`; never hand-edited

Subcommands:
    init      -- scaffold the knowledge/ directory (idempotent, non-destructive)
    validate  -- schema-validate sources/registry.yaml (read-only)
    lint      -- lint pages/ and proposals/ (read-only)
    index     -- regenerate index.md and append one log.md row (the only
                 overwriting command)
    draft     -- write ONE new proposal skeleton under proposals/ (exclusive
                 create; never touches pages/)
    export    -- serialize selected pages into one explicit, budget-capped
                 bundle file OUTSIDE the knowledge tree

Design constraints:
    - deterministic: sorted traversal, stable output, no network, no cache
      state; every run re-reads the registry and pages fresh
    - stdlib-only (Python 3.10+); page/registry content is DATA, never executed
    - frontmatter and the registry use a RESTRICTED YAML subset parsed by a
      bounded parser (see _parse_restricted_yaml): flat mappings, lists of
      scalars, lists of flat mappings, and block scalars. Anchors, aliases,
      tags, flow mappings, and nested mappings are rejected. All scalars are
      strings; timestamps are validated by grammar, not type resolution.
    - the lint is a tripwire, not a semantic-injection guarantee; pages stay
      untrusted-derived until reviewed regardless of a clean lint pass
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import unicodedata
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import quote, unquote

DEFAULT_ROOT = Path.cwd() / "knowledge"

# Enum surfaces are deliberately small; extend through your own review process.
TRUST_LEVELS = {
    "untrusted_external",
    "untrusted_derived",
    "derived_review_required",
    "reviewed_internal",
}
SOURCE_KINDS = {
    "external_research",
    "internal_doc",
    "transcript",
    "pull_request",
    "report",
    "code_excerpt",
}
ALLOWED_USES = {"research_context", "synthesis_source", "reference"}
# Echo-loop guard provenance: a registry entry's lineage is OPTIONAL and, when
# present, must be one of these two values. An absent field is a valid entry;
# downstream consumers should treat absence as "derived" (fail-closed).
PROVENANCE_LINEAGES = {"independent", "derived"}
PAGE_STATUSES = {"draft", "review", "reviewed", "archived"}
PAGE_KINDS = {"synthesis", "entity", "concept", "contradiction_note"}
# Review-routing fields. Missing `impact` means `normal` (explicit policy);
# `author`/`reviewer` are free strings compared via _fold — an independent
# review is a PROCESS property, deliberately NOT faked in lint.
PAGE_IMPACTS = {"normal", "high"}

SOURCE_ID_RE = re.compile(r"^[a-z0-9][a-z0-9_.-]{2,127}$")
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")

# Trust lattice: a page's declared trust may not exceed the ceiling imposed by
# the WEAKEST source it cites, in frontmatter or body.
PAGE_TRUST_RANK = {
    "untrusted_external": 0,
    "untrusted_derived": 0,
    "derived_review_required": 1,
    "reviewed_internal": 2,
}
SOURCE_TRUST_CEILING = {
    "untrusted_external": "derived_review_required",
    "untrusted_derived": "derived_review_required",
    "derived_review_required": "derived_review_required",
    "reviewed_internal": "reviewed_internal",
}


def _enum_check(container: dict, field: str, allowed: set, owner: str) -> list[str]:
    """Type-then-membership check for untrusted enum fields.

    Every value parsed from registry or page frontmatter is
    attacker-influenced data; a non-string value must yield a violation,
    never a TypeError at a set-membership or regex site.
    """
    value = container.get(field)
    if value is None:
        return []  # missing-field reporting is the caller's concern
    if not isinstance(value, str):
        return [f"{owner}: {field} must be a string, got {type(value).__name__}"]
    if value not in allowed:
        return [f"{owner}: {field} not in {sorted(allowed)}"]
    return []


# Explicit, bounded carve-out for genuinely directive text. Markers must pair,
# must not nest, and the section is size-capped so a page cannot exempt its
# whole body from the imperative scan.
ALLOWED_SECTION_START = "<!-- allowed-directives:start -->"
ALLOWED_SECTION_END = "<!-- allowed-directives:end -->"
ALLOWED_SECTION_MAX_LINES = 40
ALLOWED_SECTION_MAX_COUNT = 2  # per page

# Word-anchored, case-insensitive imperative / prompt-injection tripwires.
# Conservative by design (bounded false positives); extend via review.
# Patterns are matched against NFKC-folded text with format chars removed.
IMPERATIVE_PATTERNS = tuple(
    re.compile(p, re.IGNORECASE)
    for p in (
        r"\bignore\s+(?:all\s+|any\s+)?(?:previous|prior|above)\s+(?:instructions|context|directives|rules)\b",
        r"\bdisregard\s+(?:the\s+)?(?:previous|prior|above|earlier)\b",
        r"\byou\s+(?:must|should)\s+now\b",
        r"\bexecute\s+the\s+following\b",
        r"\brun\s+this\s+command\b",
        r"\bnew\s+system\s+prompt\b",
        r"\bbegin\s+(?:system|developer)\s+(?:prompt|message|instructions)\b",
        r"\bas\s+your\s+(?:new\s+)?(?:system|developer)\s+(?:prompt|instructions)\b",
    )
)

# Zero-width and bidirectional control characters have no legitimate use in
# compiled knowledge pages; their presence is flagged outright (they are the
# canonical way to smuggle text past pattern scans and human reviewers).
_FORBIDDEN_CHARS_RE = re.compile(
    "[​‌‍‎‏⁠⁡⁢⁣⁤"
    "‪‫‬‭‮⁦⁧⁨⁩﻿]"
)

# Reference-style definitions: `[ref]: target "optional title"` — their
# targets are link-linted too, so switching Markdown syntax cannot bypass
# the broken-internal-link check.
_MD_REF_DEF_RE = re.compile(
    r"""^\s{0,3}\[([^\]^\n]+)\]:\s*<?([^\s>]+)>?""", re.MULTILINE
)
# Reference USES: full `[text][label]` and collapsed `[label][]` count as
# uses; bare shortcut `[label]` does NOT (indistinguishable from claim
# markers and plain brackets). Labels match case-insensitively after
# whitespace-normalization, per CommonMark.
_MD_REF_USE_RE = re.compile(r"\]\[([^\]]+)\]|\[([^\]]+)\]\[\]")


def _norm_label(label: str) -> str:
    return re.sub(r"\s+", " ", label.strip()).casefold()


# Inline code spans delimit with EQUAL-length backtick runs (CommonMark).
_CODE_SPAN_RE = re.compile(r"(?<!`)(`+)(?!`)([^\n]+?)(?<!`)\1(?!`)")
# Any RFC-3986 scheme (ftp:, mailto:, data:, ...) or a protocol-relative
# reference is external; filesystem checks apply only to local paths.
_URI_SCHEME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9+.-]*:")


def _find_inline_link_targets(text: str) -> list[str]:
    """Extract inline-link destinations with balanced/escaped parentheses.

    A regex terminating at the first ')' truncates `[x](foo(1).md)`; this
    scanner tracks paren depth, honors backslash escapes, `<...>`
    destinations, and stops the destination at depth-1 whitespace (the
    optional title).
    """
    targets: list[str] = []
    i = 0
    while True:
        j = text.find("](", i)
        if j < 0:
            return targets
        k = j + 2
        while k < len(text) and text[k] in " \t":
            k += 1
        if k < len(text) and text[k] == "<":
            end = text.find(">", k + 1)
            if end < 0:
                i = j + 2
                continue
            targets.append(text[k + 1:end])
            i = end + 1
            continue
        depth = 1
        dest: list[str] = []
        while k < len(text):
            c = text[k]
            if c == "\\" and k + 1 < len(text):
                dest.append(text[k + 1])
                k += 2
                continue
            if c == "(":
                depth += 1
                dest.append(c)
            elif c == ")":
                depth -= 1
                if depth == 0:
                    break
                dest.append(c)
            elif c in " \t" and depth == 1:
                # Optional title begins; skip to the matching close paren.
                while k < len(text):
                    if text[k] == "(":
                        depth += 1
                    elif text[k] == ")":
                        depth -= 1
                        if depth == 0:
                            break
                    k += 1
                break
            elif c == "\n":
                break  # destinations do not span lines
            else:
                dest.append(c)
            k += 1
        if dest:
            targets.append("".join(dest))
        i = k + 1


def _extract_link_targets(body: str) -> list[tuple[str, bool]]:
    """Return (target, contributes_inbound) pairs from rendered text.

    Inline links always contribute an inbound reference to their target.
    Reference DEFINITIONS are always validity-checked (broken targets flag
    regardless), but contribute inbound only when their label is actually
    used (an unused `[unused]: b.md` must not cure b.md's orphan status).
    Inline CODE SPANS are literal text, not rendered links or reference
    uses, and are removed from this surface first.
    """
    rendered = _CODE_SPAN_RE.sub(" ", body)
    used = {
        _norm_label(a or b) for a, b in _MD_REF_USE_RE.findall(rendered)
    }
    pairs: list[tuple[str, bool]] = [
        (t, True) for t in _find_inline_link_targets(rendered)
    ]
    for label, target in _MD_REF_DEF_RE.findall(rendered):
        pairs.append((target, _norm_label(label) in used))
    return pairs


# Claim-marker grammar: every substantive claim is cited, or marked as
# inference / design proposal / unknown-unresolved. Deterministic
# approximation: every prose block outside allowed sections must carry one.
CLAIM_MARKER_RE = re.compile(
    r"\[(?:source:\s*[a-z0-9_.-]+|inference|proposal|unknown|unresolved)\]",
    re.IGNORECASE,
)
_CITED_SOURCE_RE = re.compile(r"\[source:\s*([a-z0-9_.-]+)\]", re.IGNORECASE)
_CLAIM_MIN_CHARS = 40  # blocks shorter than this are not "substantive"

# One visible claim marker authorizes at most this much visible claim content
# page-wide; longer content needs proportionally more markers (bounds both the
# hidden-marker long-tail bypass and sub-threshold fragmentation).
_CLAIM_CHARS_PER_MARKER = 300


def _fold(text: str) -> str:
    """Strip ALL format (Cf) characters, then NFKC-fold, before matching.

    Category-wide Cf stripping (soft hyphen, ZWJ variants, bidi controls,
    anything future) closes the listed-chars-only gap. Confusables and
    homoglyphs remain out of scope: this is a tripwire.
    """
    stripped = "".join(
        c for c in text if unicodedata.category(c) != "Cf"
    )
    return unicodedata.normalize("NFKC", stripped)


def _sanitize_cell(value: object) -> str:
    """Make a value safe for one generated markdown table/log row.

    Newlines/pipes break row structure; link metacharacters would let
    untrusted frontmatter inject live markup into the generated catalog,
    so both classes are stripped, not escaped.
    """
    text = re.sub(r"[\r\n|]+", " ", str(value))
    return re.sub(r"[\[\]()<>`]", "", text).strip()


def _utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# --------------------------------------------------------------------------
# restricted YAML subset (bounded, stdlib-only)
# --------------------------------------------------------------------------
#
# Supported shapes (everything the registry and page frontmatter need):
#   key: scalar                    -> str (quotes stripped; "..." via JSON)
#   key: [a, b]                    -> list[str] (inline; [] allowed)
#   key:                           -> followed by an indented block list of
#     - scalar                        scalars, or of flat mappings whose
#     - key: value                    values are scalars, block scalars, or
#       other: value                  one nested block list of scalars
#   key: |  /  key: >              -> block scalar, folded to ONE string
# Rejected outright (violation, never execution or recursion): anchors,
# aliases, tags, flow mappings, nested mappings, tab indentation, and
# duplicate keys. All scalars are returned as STRINGS — no int/bool/date
# resolution, so timestamp policy is enforced by grammar checks, not types.

_UNSUPPORTED_VALUE_RE = re.compile(r"^[&*!{?]")


def _parse_scalar(raw: str) -> tuple[str | None, str | None]:
    """Parse one restricted scalar; returns (value, error)."""
    s = raw.strip()
    if not s:
        return "", None
    if _UNSUPPORTED_VALUE_RE.match(s):
        return None, f"unsupported YAML feature in value {s[:20]!r} (restricted parser)"
    if s.startswith('"'):
        try:
            decoded = json.loads(s)
        except ValueError:
            return None, f"unparseable double-quoted scalar {s[:40]!r}"
        if not isinstance(decoded, str):
            return None, f"double-quoted scalar decoded to {type(decoded).__name__}"
        return decoded, None
    if s.startswith("'"):
        if len(s) >= 2 and s.endswith("'"):
            return s[1:-1].replace("''", "'"), None
        return None, f"unterminated single-quoted scalar {s[:40]!r}"
    # Plain scalar: strip a trailing comment only when whitespace-separated
    # (so URL fragments like page#frag survive).
    s = re.sub(r"\s+#.*$", "", s).strip()
    return s, None


def _parse_inline_list(raw: str) -> tuple[list[str] | None, str | None]:
    inner = raw.strip()[1:-1].strip()
    if not inner:
        return [], None
    items: list[str] = []
    for part in inner.split(","):
        value, err = _parse_scalar(part)
        if err:
            return None, err
        items.append(value)
    return items, None


_KEY_RE = re.compile(r"^([A-Za-z0-9_][A-Za-z0-9_.-]*):(.*)$")


class _Lines:
    """Cursor over raw lines with 1-based numbering for error messages."""

    def __init__(self, text: str) -> None:
        self.lines = text.splitlines()
        self.pos = 0

    def peek(self) -> str | None:
        return self.lines[self.pos] if self.pos < len(self.lines) else None

    def take(self) -> str:
        line = self.lines[self.pos]
        self.pos += 1
        return line


def _indent_of(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def _collect_block_scalar(cur: _Lines, style: str, parent_indent: int) -> str:
    """Fold a `|` or `>` block scalar into ONE plain string."""
    collected: list[str] = []
    while True:
        line = cur.peek()
        if line is None:
            break
        if line.strip() and _indent_of(line) <= parent_indent:
            break
        cur.take()
        collected.append(line.strip())
    joiner = "\n" if style == "|" else " "
    return joiner.join(c for c in collected if c).strip()


def _parse_mapping_body(
    cur: _Lines, indent: int, owner: str, depth: int
) -> tuple[dict | None, str | None]:
    """Parse `key: value` lines at exactly `indent` into a flat mapping."""
    result: dict[str, object] = {}
    while True:
        line = cur.peek()
        if line is None:
            break
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            cur.take()
            continue
        if "\t" in line[:_indent_of(line)]:
            return None, f"{owner}: tab indentation is not supported"
        line_indent = _indent_of(line)
        if line_indent < indent:
            break
        if line_indent > indent:
            return None, (
                f"{owner}: nested mapping at indent {line_indent} is not "
                f"supported (restricted parser)"
            )
        m = _KEY_RE.match(stripped)
        if not m:
            if stripped.startswith("- "):
                break  # caller's list context resumes
            return None, f"{owner}: unparseable line {stripped[:40]!r}"
        key, rest = m.group(1), m.group(2).strip()
        cur.take()
        if key in result:
            return None, f"{owner}: duplicate key {key!r}"
        if rest in ("|", ">", "|-", ">-", "|+", ">+"):
            result[key] = _collect_block_scalar(cur, rest[0], indent)
            continue
        if rest.startswith("[") and rest.endswith("]"):
            items, err = _parse_inline_list(rest)
            if err:
                return None, f"{owner}: {key}: {err}"
            result[key] = items
            continue
        if rest:
            value, err = _parse_scalar(rest)
            if err:
                return None, f"{owner}: {key}: {err}"
            result[key] = value
            continue
        # Empty value: an indented block list, or genuinely empty.
        nxt = cur.peek()
        while nxt is not None and (not nxt.strip() or nxt.strip().startswith("#")):
            cur.take()
            nxt = cur.peek()
        if nxt is None or _indent_of(nxt) <= indent or not nxt.strip().startswith("- "):
            result[key] = ""
            continue
        if depth >= 2:
            return None, f"{owner}: {key}: list nesting too deep (restricted parser)"
        lst, err = _parse_block_list(cur, _indent_of(nxt), owner, depth + 1)
        if err:
            return None, err
        result[key] = lst
    return result, None


def _parse_block_list(
    cur: _Lines, indent: int, owner: str, depth: int
) -> tuple[list | None, str | None]:
    """Parse `- item` lines at exactly `indent`; items are scalars or flat
    mappings (mappings only at depth 1, i.e. a top-level list of entries)."""
    items: list[object] = []
    while True:
        line = cur.peek()
        if line is None:
            break
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            cur.take()
            continue
        line_indent = _indent_of(line)
        if line_indent != indent or not stripped.startswith("- "):
            if line_indent >= indent and stripped.startswith("- "):
                return None, f"{owner}: misindented list item {stripped[:40]!r}"
            break
        cur.take()
        item_text = stripped[2:].strip()
        m = _KEY_RE.match(item_text)
        if m and depth == 1:
            # List item opens a flat mapping: `- key: value` plus following
            # lines indented past the dash.
            key, rest = m.group(1), m.group(2).strip()
            entry: dict[str, object] = {}
            if rest in ("|", ">", "|-", ">-", "|+", ">+"):
                # Ambiguous continuation indent; require the block scalar on
                # its own continuation line instead.
                return None, (
                    f"{owner}: {key}: block scalar directly on a list-item "
                    f"line is not supported (restricted parser); put the key "
                    f"on a continuation line"
                )
            elif rest.startswith("[") and rest.endswith("]"):
                lst, err = _parse_inline_list(rest)
                if err:
                    return None, f"{owner}: {key}: {err}"
                entry[key] = lst
            else:
                value, err = _parse_scalar(rest)
                if err:
                    return None, f"{owner}: {key}: {err}"
                entry[key] = value
            nxt = cur.peek()
            while nxt is not None and (
                not nxt.strip() or nxt.strip().startswith("#")
            ):
                cur.take()
                nxt = cur.peek()
            if nxt is not None and _indent_of(nxt) > indent and not nxt.strip().startswith("- "):
                rest_map, err = _parse_mapping_body(
                    cur, _indent_of(nxt), owner, depth
                )
                if err:
                    return None, err
                for k, v in rest_map.items():
                    if k in entry:
                        return None, f"{owner}: duplicate key {k!r}"
                    entry[k] = v
            items.append(entry)
            continue
        value, err = _parse_scalar(item_text)
        if err:
            return None, f"{owner}: {err}"
        items.append(value)
    return items, None


def _parse_restricted_yaml(text: str, owner: str) -> tuple[dict | None, str | None]:
    """Parse the restricted subset; returns (mapping, error)."""
    cur = _Lines(text)
    mapping, err = _parse_mapping_body(cur, 0, owner, 0)
    if err:
        return None, err
    remaining = cur.peek()
    if remaining is not None:
        return None, f"{owner}: unparseable trailing line {remaining.strip()[:40]!r}"
    return mapping, None


_SAFE_PLAIN_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9 _./:@+-]*$")


def _emit_scalar(value: str) -> str:
    """Emit a scalar that the restricted parser round-trips exactly."""
    if _SAFE_PLAIN_RE.match(value) and "  " not in value and value == value.strip() and "#" not in value:
        return value
    return json.dumps(value, ensure_ascii=False)


# --------------------------------------------------------------------------
# registry
# --------------------------------------------------------------------------

def load_registry(root: Path) -> tuple[dict, list[str]]:
    """Parse sources/registry.yaml; returns (registry-mapping, violations)."""
    path = root / "sources" / "registry.yaml"
    violations: list[str] = []
    if not path.is_file():
        return {}, [f"registry missing: {path}"]
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        return {}, [f"registry unreadable ({exc.__class__.__name__})"]
    data, err = _parse_restricted_yaml(text, "registry")
    if err:
        return {}, [f"registry unparseable: {err}"]
    if not isinstance(data, dict) or not isinstance(data.get("sources"), list):
        return {}, ["registry must be a mapping with a top-level 'sources' list"]

    seen: dict[str, dict] = {}
    for i, entry in enumerate(data["sources"]):
        where = f"sources[{i}]"
        if not isinstance(entry, dict):
            violations.append(f"{where}: entry must be a mapping")
            continue
        sid = entry.get("source_id")
        if not isinstance(sid, str) or not SOURCE_ID_RE.match(sid):
            violations.append(f"{where}: bad or missing source_id")
            continue
        if sid in seen:
            violations.append(f"{where}: duplicate source_id {sid}")
            continue
        for field in ("kind", "location", "retrieved_at", "trust", "allowed_use"):
            if not entry.get(field):
                violations.append(f"{sid}: missing required field '{field}'")
        violations.extend(_enum_check(entry, "kind", SOURCE_KINDS, sid))
        violations.extend(_enum_check(entry, "trust", TRUST_LEVELS, sid))
        violations.extend(_enum_check(entry, "allowed_use", ALLOWED_USES, sid))
        retrieved = entry.get("retrieved_at")
        if retrieved is not None:
            if not isinstance(retrieved, str):
                violations.append(f"{sid}: retrieved_at must be an ISO-8601 string")
            elif not _valid_iso_timestamp(retrieved):
                violations.append(f"{sid}: retrieved_at is not ISO-8601")
        location = entry.get("location")
        if location is not None and not isinstance(location, str):
            violations.append(f"{sid}: location must be a string scalar")
        reason = entry.get("unhashed_reason")
        if reason is not None and not isinstance(reason, str):
            violations.append(f"{sid}: unhashed_reason must be a string scalar")
        sha = entry.get("content_sha256")
        if sha is None or sha == "":
            if not reason:
                violations.append(
                    f"{sid}: content_sha256 absent and no unhashed_reason given"
                )
        elif not isinstance(sha, str) or not SHA256_RE.match(sha):
            violations.append(f"{sid}: content_sha256 is not 64 lowercase hex chars")
        # Echo-loop guard provenance: `provenance_lineage` is optional
        # (absent = effective "derived", fail-closed by construction) BUT an
        # entry declared `independent` MUST carry a non-empty
        # `upstream_attestation` naming its upstream — otherwise two
        # unattested registrations of the same upstream would each count as
        # a distinct corroboration unit.
        violations.extend(
            _enum_check(entry, "provenance_lineage", PROVENANCE_LINEAGES, sid)
        )
        attestation = entry.get("upstream_attestation")
        if attestation is not None and (
            not isinstance(attestation, str) or not attestation.strip()
        ):
            violations.append(
                f"{sid}: upstream_attestation must be a non-empty string scalar"
            )
        if entry.get("provenance_lineage") == "independent" and not (
            isinstance(attestation, str) and attestation.strip()
        ):
            violations.append(
                f"{sid}: provenance_lineage independent requires a non-empty "
                "upstream_attestation naming its upstream"
            )
        seen[sid] = entry
    return seen, violations


# --------------------------------------------------------------------------
# pages
# --------------------------------------------------------------------------

def _iter_pages(root: Path) -> tuple[list[Path], list[str]]:
    pages_dir = (root / "pages").resolve()
    violations: list[str] = []
    pages: list[Path] = []
    if not pages_dir.is_dir():
        return [], [f"pages directory missing: {pages_dir}"]
    for p in sorted(pages_dir.rglob("*.md")):
        try:
            resolved = p.resolve()
        except (OSError, RuntimeError):  # symlink loop -> violation
            violations.append(f"{p.name}: unresolvable path (symlink loop?)")
            continue
        if not str(resolved).startswith(str(pages_dir) + os.sep) and resolved != pages_dir:
            violations.append(f"{p.name}: escapes pages/ after symlink resolution")
            continue
        if not resolved.is_file():
            violations.append(
                f"{p.name}: does not resolve to a regular readable file"
            )
            continue
        pages.append(p)
    return pages, violations


def _read_page(page: Path, name: str) -> tuple[str | None, list[str]]:
    """Read a page; any I/O or decode failure is a violation, not a crash."""
    try:
        return page.read_text(encoding="utf-8"), []
    except (OSError, UnicodeDecodeError) as exc:
        return None, [f"{name}: unreadable page ({exc.__class__.__name__})"]


def _split_frontmatter(text: str, name: str) -> tuple[dict | None, str, list[str]]:
    if not text.startswith("---\n"):
        return None, text, [f"{name}: missing YAML frontmatter"]
    end = text.find("\n---", 4)
    if end < 0:
        return None, text, [f"{name}: unterminated frontmatter"]
    raw = text[4:end]
    body = text[end + 4:]
    fm, err = _parse_restricted_yaml(raw, name)
    if err:
        return None, body, [f"{name}: frontmatter unparseable: {err}"]
    if not isinstance(fm, dict):
        return None, body, [f"{name}: frontmatter must be a mapping"]
    return fm, body, []


def _scan_imperatives(text: str, name: str, where: str) -> list[str]:
    folded = _fold(text)
    hits = []
    for pat in IMPERATIVE_PATTERNS:
        m = pat.search(folded)
        if m:
            hits.append(
                f"{name}: imperative/prompt-injection pattern in {where}: "
                f"'{m.group(0)[:60]}'"
            )
    return hits


def _scrub_comments(line: str, in_comment: bool) -> tuple[str, bool]:
    """Return (visible text of line, new comment-state), char-accurate."""
    out: list[str] = []
    i = 0
    while i < len(line):
        if in_comment:
            end = line.find("-->", i)
            if end < 0:
                return "".join(out), True
            in_comment = False
            i = end + 3
        else:
            start = line.find("<!--", i)
            if start < 0:
                out.append(line[i:])
                break
            out.append(line[i:start])
            in_comment = True
            i = start + 4
    return "".join(out), in_comment


class _BodyAnalysis:
    """Single-pass line-classifier over a page body: one state machine shared
    by the claim lint, imperative scan, and allowed-section handling.

    States: fence, html_comment, allowed_section, prose. Visibility for
    claim/marker purposes excludes fenced code and comment content; the
    imperative scan surface excludes ONLY allowed sections (fences and
    comments stay scanned — injection hides there). Allowed sections carve
    out imperatives, never citations.
    """

    def __init__(self, body: str, name: str) -> None:
        self.name = name
        self.violations: list[str] = []
        self.imperative_lines: list[str] = []
        self.claim_runs: list[tuple[str, int]] = []  # (content, markers)
        self.total_claim_chars = 0
        self.total_markers = 0
        # Rendered (non-fence, comment-scrubbed) text: the single surface
        # for citations, trust pinning, and link extraction (fenced or
        # commented examples are neither citations nor links).
        self._visible_lines: list[str] = []
        self._run_content: list[str] = []
        self._run_markers = 0
        self._analyze(body)
        self.visible_text = "\n".join(self._visible_lines)

    def _close_run(self) -> None:
        content = " ".join(s for s in self._run_content if s)
        if content:
            self.claim_runs.append((content, self._run_markers))
        self._run_content = []
        self._run_markers = 0

    def _analyze(self, body: str) -> None:
        in_fence = False
        fence_char = "`"
        fence_len = 3
        in_comment = False
        in_section = False
        section_count = 0
        section_lines_total = 0
        for raw in body.splitlines():
            # Allowed-section markers are themselves HTML comments, so they
            # must be recognized on the RAW line before comment scrubbing —
            # but never from inside a fence or a continuing comment.
            raw_stripped = raw.strip()
            if not in_comment and not in_fence:
                if raw_stripped == ALLOWED_SECTION_START:
                    if in_section:
                        self.violations.append(
                            f"{self.name}: nested allowed-directives section"
                        )
                    in_section = True
                    section_count += 1
                    if section_count > ALLOWED_SECTION_MAX_COUNT:
                        self.violations.append(
                            f"{self.name}: more than {ALLOWED_SECTION_MAX_COUNT} "
                            f"allowed-directives sections"
                        )
                    continue
                if raw_stripped == ALLOWED_SECTION_END:
                    if not in_section:
                        self.violations.append(
                            f"{self.name}: allowed-directives end without start"
                        )
                    in_section = False
                    continue

            visible, new_comment = _scrub_comments(raw, in_comment)
            in_comment_line = in_comment or new_comment
            in_comment = new_comment
            stripped = visible.strip()

            # Fence state: a fence line is a run of 3+ identical backticks
            # or tildes indented at most 3 spaces (4+ spaces is indented
            # code, not a fence), outside comments. The opening delimiter's
            # char and length are recorded; only a run of the SAME char at
            # least as long, with nothing else on the line, closes it.
            fence_eligible = bool(re.match(r"^ {0,3}\S", visible))
            if not in_comment_line and not in_fence and fence_eligible:
                m = re.match(r"^(`{3,}|~{3,})", stripped)
                if m:
                    in_fence = True
                    fence_char = m.group(1)[0]
                    fence_len = len(m.group(1))
                    self._close_run()
                    self.imperative_lines.append(raw)
                    continue
            elif not in_comment_line and in_fence:
                if fence_eligible and re.fullmatch(
                    rf"{re.escape(fence_char)}{{{fence_len},}}\s*", stripped
                ):
                    in_fence = False
                    self._close_run()
                    self.imperative_lines.append(raw)
                    continue

            if in_section:
                section_lines_total += 1
                if section_lines_total == ALLOWED_SECTION_MAX_LINES + 1:
                    self.violations.append(
                        f"{self.name}: allowed-directives content exceeds "
                        f"{ALLOWED_SECTION_MAX_LINES} lines per page"
                    )
            else:
                # Everything outside allowed sections is imperative-scanned,
                # including fence and comment content (raw line, deliberately).
                self.imperative_lines.append(raw)

            if in_fence:
                self._close_run()
                continue

            self._visible_lines.append(visible)

            if not stripped:
                self._close_run()
                continue

            # Markers count only when visible (comments already scrubbed).
            line_markers = len(CLAIM_MARKER_RE.findall(visible))
            self.total_markers += line_markers

            if stripped.startswith("#"):
                # Headings are labels, but a substantive heading is still a
                # claim: at >= _CLAIM_MIN_CHARS it needs a marker and counts
                # toward page density.
                heading_text = stripped.lstrip("#").strip()
                if len(heading_text) >= _CLAIM_MIN_CHARS:
                    self.total_claim_chars += len(heading_text)
                    if not CLAIM_MARKER_RE.search(visible):
                        self.violations.append(
                            f"{self.name}: claim-length heading without "
                            f"marker: '{heading_text[:60]}...'"
                        )
                self._close_run()
                continue
            if re.fullmatch(r"\|[\s:|-]+\|?", stripped):
                continue  # table separator row
            content = re.sub(r"^[>|\s]+", "", stripped).strip("| ")
            if content:
                self._run_content.append(content)
                self._run_markers += line_markers
                self.total_claim_chars += len(content)
        self._close_run()
        if in_comment:
            self.violations.append(f"{self.name}: unterminated HTML comment")
        if in_fence:
            self.violations.append(f"{self.name}: unterminated code fence")
        if in_section:
            self.violations.append(
                f"{self.name}: unterminated allowed-directives section"
            )


def _lint_claims(analysis: "_BodyAnalysis", name: str,
                 registry: dict) -> list[str]:
    """Citation rules over the analyzed body.

    Local rule: every claim run of >= _CLAIM_MIN_CHARS visible chars needs a
    marker INSIDE that run (a marker in a fence, comment, or another run
    cannot vouch for it). Global rule: total visible claim content needs one
    marker per _CLAIM_CHARS_PER_MARKER chars, so sub-threshold fragmentation
    cannot aggregate uncited meaning.
    """
    violations: list[str] = []
    for content, markers in analysis.claim_runs:
        if len(content) >= _CLAIM_MIN_CHARS and markers == 0:
            violations.append(
                f"{name}: uncited claim run (no visible marker inside it): "
                f"'{content[:60]}...'"
            )
    if analysis.total_claim_chars >= _CLAIM_MIN_CHARS:
        required = 1 + (analysis.total_claim_chars - 1) // _CLAIM_CHARS_PER_MARKER
        if analysis.total_markers < required:
            violations.append(
                f"{name}: under-cited page ({analysis.total_markers} visible "
                f"marker(s), {required} required for "
                f"{analysis.total_claim_chars} visible claim chars)"
            )
    # Only VISIBLE citations are claims; a fenced example citing a ghost id
    # is documentation, not a citation.
    for sid in _CITED_SOURCE_RE.findall(analysis.visible_text):
        if sid not in registry:
            violations.append(
                f"{name}: claim cites unregistered source_id '{sid}'"
            )
    return violations


def _iter_fm_strings(value: object, path: str = "frontmatter"):
    """Yield (path, string) for every string nested anywhere in frontmatter.

    The restricted parser cannot produce cycles (no anchors/aliases), so a
    bounded walk suffices.
    """
    if isinstance(value, str):
        yield path, value
        return
    if isinstance(value, dict):
        for k, v in sorted(value.items(), key=lambda kv: str(kv[0])):
            if isinstance(k, str):
                yield f"{path} key", k
            yield from _iter_fm_strings(v, f"{path}.{k}")
    elif isinstance(value, (list, tuple)):
        for i, v in enumerate(value):
            yield from _iter_fm_strings(v, f"{path}[{i}]")


def _lint_review_fields(fm: dict, name: str) -> list[str]:
    """Review-consistency tripwires (schema checks, NOT a review).

    Rules: status reviewed requires reviewer + ISO last_reviewed; trust
    reviewed_internal requires status reviewed (trust<->status coupling);
    impact high + status reviewed additionally requires author, and
    reviewer must differ from author under fold+casefold equality
    (homoglyph self-review is a documented residual — your review process
    owns it). status archived freezes fields: no additional gates.
    """
    violations: list[str] = []
    status = fm.get("status")
    if fm.get("trust") == "reviewed_internal" and status != "reviewed":
        violations.append(
            f"{name}: trust reviewed_internal requires status reviewed"
        )
    if status != "reviewed":
        return violations
    reviewer = fm.get("reviewer")
    if not isinstance(reviewer, str) or not reviewer.strip():
        violations.append(f"{name}: status reviewed requires a reviewer string")
        reviewer = None
    last = fm.get("last_reviewed")
    if isinstance(last, str) and last.strip():
        if not _valid_iso_timestamp(last):
            violations.append(f"{name}: last_reviewed is not ISO-8601")
    else:
        violations.append(
            f"{name}: status reviewed requires an ISO-8601 last_reviewed"
        )
    if fm.get("impact") == "high":
        author = fm.get("author")
        if not isinstance(author, str) or not author.strip():
            violations.append(
                f"{name}: impact high + reviewed requires an author string"
            )
        elif reviewer is not None and (
            _fold(reviewer).casefold().strip()
            == _fold(author).casefold().strip()
        ):
            violations.append(
                f"{name}: high-impact page reviewed by its own author "
                f"('{author}') — distinct reviewer required"
            )
    return violations


def lint_pages(root: Path, registry: dict) -> list[str]:
    pages, violations = _iter_pages(root)
    _pages_dir = (root / "pages").resolve()
    page_names = {p.resolve().relative_to(_pages_dir).as_posix() for p in pages}
    referenced: set[str] = set()

    for page in pages:
        name = page.name
        text, read_violations = _read_page(page, name)
        if text is None:
            violations.extend(read_violations)
            continue

        if _FORBIDDEN_CHARS_RE.search(text):
            violations.append(
                f"{name}: contains zero-width or bidi control characters"
            )

        fm, body, fm_violations = _split_frontmatter(text, name)
        violations.extend(fm_violations)
        analysis = _BodyAnalysis(body, name)

        if fm is not None:
            for field in ("title", "status", "kind", "source_ids", "trust"):
                if not fm.get(field):
                    violations.append(f"{name}: frontmatter missing '{field}'")
            violations.extend(_enum_check(fm, "status", PAGE_STATUSES, name))
            violations.extend(_enum_check(fm, "kind", PAGE_KINDS, name))
            violations.extend(_enum_check(fm, "trust", TRUST_LEVELS, name))
            violations.extend(_enum_check(fm, "impact", PAGE_IMPACTS, name))
            violations.extend(_lint_review_fields(fm, name))

            source_ids = fm.get("source_ids") or []
            if not isinstance(source_ids, list):
                violations.append(f"{name}: source_ids must be a list")
                source_ids = []
            cited: set[str] = set()
            for sid in source_ids:
                if not isinstance(sid, str):
                    violations.append(
                        f"{name}: source_ids entry is not a string: {sid!r}"
                    )
                elif sid not in registry:
                    violations.append(f"{name}: cites unregistered source_id '{sid}'")
                else:
                    cited.add(sid)
            # VISIBLE body [source:] citations count toward trust too —
            # declaring only trusted sources in frontmatter while citing a
            # weaker one inline must not evade the pin; fenced or commented
            # example citations do NOT count.
            cited.update(
                s for s in _CITED_SOURCE_RE.findall(analysis.visible_text)
                if s in registry
            )
            # Trust lattice: page trust may not exceed the ceiling of its
            # weakest cited source. Frontmatter is data, not authorization.
            page_trust = fm.get("trust")
            if cited and isinstance(page_trust, str) and page_trust in PAGE_TRUST_RANK:
                ceilings = [
                    SOURCE_TRUST_CEILING.get(str(registry[s].get("trust")), "derived_review_required")
                    for s in cited
                ]
                weakest = min(ceilings, key=lambda c: PAGE_TRUST_RANK[c])
                if PAGE_TRUST_RANK[page_trust] > PAGE_TRUST_RANK[weakest]:
                    violations.append(
                        f"{name}: trust '{page_trust}' exceeds ceiling "
                        f"'{weakest}' imposed by its weakest cited source"
                    )
            # Every string nested anywhere in frontmatter shares the
            # imperative scan surface (not just top-level values).
            for where, value in _iter_fm_strings(fm):
                violations.extend(_scan_imperatives(value, name, where))

        violations.extend(analysis.violations)
        violations.extend(
            _scan_imperatives("\n".join(analysis.imperative_lines), name, "body")
        )
        violations.extend(_lint_claims(analysis, name, registry))

        # Links are extracted from the VISIBLE surface only: fenced markdown
        # examples and commented-out links are not rendered links.
        for target, contributes_inbound in _extract_link_targets(
            analysis.visible_text
        ):
            # Any URI scheme or protocol-relative reference is external and
            # gets no filesystem checks; '#' is a same-page anchor.
            if target.startswith(("#", "//")) or _URI_SCHEME_RE.match(target):
                continue
            # Decode, then contain: percent-encoding must not smuggle
            # traversal past the realpath containment check. Parent-relative
            # links between nested sibling dirs are legitimate; containment,
            # not lexical '..', decides.
            fs_target = unquote(re.split(r"[#?]", target, maxsplit=1)[0])
            if not fs_target:
                continue
            resolved = (page.parent / fs_target).resolve()
            pages_dir = (root / "pages").resolve()
            if not str(resolved).startswith(str(pages_dir) + os.sep):
                violations.append(f"{name}: link escapes pages/: {target}")
            elif not resolved.exists():
                violations.append(f"{name}: broken internal link: {target}")
            elif resolved != page.resolve() and contributes_inbound:
                # Self-links do not satisfy the inbound-reference
                # requirement, and unused reference definitions
                # validity-check but do not vouch for their target.
                referenced.add(resolved.relative_to(pages_dir).as_posix())

    # Orphans: only meaningful once more than one page exists.
    if len(pages) > 1:
        for rel in sorted(page_names - referenced):
            violations.append(f"{rel}: orphan page (no inbound internal link)")
    return violations


# --------------------------------------------------------------------------
# drafting workflow: proposal skeletons only, never pages/
# --------------------------------------------------------------------------

_SLUG_MAX_LEN = 60
_PROPOSAL_BANNER = (
    "<!-- UNTRUSTED PROPOSAL: draft skeleton, NOT compiled knowledge. Not\n"
    "     part of the query corpus; never listed in the index; promotion is\n"
    "     a move into knowledge/pages/ plus a clean lint, through your own\n"
    "     review process. -->"
)


def _slugify(title: str) -> str:
    """Pinned slug grammar: fold -> lower -> [a-z0-9-] -> collapse/strip.

    Deterministic and separator-free by construction; empty results are
    errors, length is capped.
    """
    folded = _fold(title).lower()
    slug = re.sub(r"-+", "-", re.sub(r"[^a-z0-9]", "-", folded)).strip("-")
    slug = slug[:_SLUG_MAX_LEN].rstrip("-")
    if not slug:
        raise SystemExit(f"draft: title produces an empty slug: {title!r}")
    return slug


def create_draft(root: Path, title: str, source_ids: list[str], kind: str,
                 registry: dict) -> Path:
    """Emit a proposal skeleton to knowledge/proposals/<slug>.md.

    Forced frontmatter (status draft, trust derived_review_required) and a
    leading UNTRUSTED banner are tool-enforced on every write; you review
    and promote manually. No auto-apply, no writes to pages/.
    """
    for sid in source_ids:
        if sid not in registry:
            raise SystemExit(f"draft: unregistered source_id: {sid}")
    if kind not in PAGE_KINDS:
        raise SystemExit(f"draft: kind not in {sorted(PAGE_KINDS)}")
    proposals = root / "proposals"
    if proposals.is_symlink():
        raise SystemExit(f"draft: proposals dir is a symlink: {proposals}")
    if proposals.exists() and not proposals.is_dir():
        raise SystemExit(
            f"draft: proposals path exists but is not a directory: {proposals}"
        )
    proposals.mkdir(exist_ok=True)
    target = proposals / f"{_slugify(title)}.md"
    fm_lines = [
        f"title: {_emit_scalar(title)}",
        "status: draft",
        f"kind: {kind}",
        "source_ids:",
        *[f"  - {sid}" for sid in source_ids],
        "trust: derived_review_required",
    ]
    body = (
        "---\n" + "\n".join(fm_lines) + f"\n---\n\n{_PROPOSAL_BANNER}\n\n"
        "## Summary\n\n"
        "State each claim with a visible marker: cited "
        "[source: " + source_ids[0] + "], or [inference], [proposal], "
        "[unknown].\n\n"
        "## Findings\n\n"
        "## Contradictions / Unresolved\n"
    )
    with _safe_create_exclusive(root, target) as fh:
        fh.write(body)
    return target


def lint_proposals(root: Path) -> list[str]:
    """Reduced lint over proposals/ (a lint-blind proposals tree would be a
    second wiki with weaker controls).

    Checks: forbidden chars, full-file imperative scan (no allowed-section
    carve-out in proposals), frontmatter parse, and a hard ban on elevated
    status (reviewed/archived) or trust (reviewed_internal) while under
    proposals/. Citation/link/orphan graphs remain pages-only.
    """
    proposals = root / "proposals"
    violations: list[str] = []
    if proposals.is_symlink():
        # A symlinked proposals/ would make an EXTERNAL directory the
        # containment base for the whole scan — refuse.
        return [f"proposals: directory is a symlink: {proposals}"]
    if proposals.exists() and not proposals.is_dir():
        return [f"proposals: path exists but is not a directory: {proposals}"]
    if not proposals.is_dir():
        return []
    proposals_res = proposals.resolve()
    for p in sorted(proposals.rglob("*.md")):
        name = f"proposals/{p.name}"
        try:
            resolved = p.resolve()
        except (OSError, RuntimeError):  # symlink loop -> violation
            violations.append(f"{name}: unresolvable path (symlink loop?)")
            continue
        if not str(resolved).startswith(str(proposals_res) + os.sep):
            violations.append(f"{name}: escapes proposals/ after resolution")
            continue
        if not resolved.is_file():
            violations.append(f"{name}: does not resolve to a regular file")
            continue
        text, read_violations = _read_page(p, name)
        if text is None:
            violations.extend(read_violations)
            continue
        if _FORBIDDEN_CHARS_RE.search(text):
            violations.append(
                f"{name}: contains zero-width or bidi control characters"
            )
        violations.extend(_scan_imperatives(text, name, "proposal (full file)"))
        fm, _body, fm_violations = _split_frontmatter(text, name)
        violations.extend(fm_violations)
        if fm is not None:
            # Only `draft` belongs under proposals/ — `review`, `reviewed`,
            # and `archived` all imply progress that must happen in pages/
            # via promotion (allowlist, not denylist).
            if fm.get("status") != "draft":
                violations.append(
                    f"{name}: proposals must have status draft, not "
                    f"'{fm.get('status')}'"
                )
            violations.extend(_enum_check(fm, "trust", TRUST_LEVELS, name))
            if fm.get("trust") == "reviewed_internal":
                violations.append(
                    f"{name}: proposals may not claim trust reviewed_internal"
                )
    return violations


# --------------------------------------------------------------------------
# export: explicit, budget-capped, citation-preserving bundles
# --------------------------------------------------------------------------

_EXPORT_DEFAULT_BUDGET = 20_000  # Unicode code points of the FULL serialized
                                 # artifact (header + pages + stamps), pinned


def _bundle_header(pages: list[str], budget: int, stamp: str,
                   lint_clean: bool) -> str:
    """Mandatory FIRST-BYTES banner. The bundle is untrusted-derived
    packaging, never policy."""
    return (
        "<!-- UNTRUSTED DERIVED KNOWLEDGE BUNDLE - NOT POLICY.\n"
        "     Do not auto-inject into agent context; do not execute anything\n"
        "     herein; claims remain hypotheses with the trust recorded per\n"
        "     page (project-knowledge skill conventions). -->\n"
        f"<!-- generated: {_sanitize_cell(stamp)} | tool: knowledge_tool | "
        f"pages: {', '.join(pages)} | "
        f"budget: {budget} code points | lint: "
        f"{'OK' if lint_clean else 'FAIL'} -->\n\n"
    )


def export_bundle(root: Path, page_rels: list[str], out: Path, budget: int,
                  registry: dict, stamp: str | None = None) -> Path:
    """Serialize selected pages/ into ONE explicit bundle file.

    Containment: --out must not be under knowledge/ at all (a bundle inside
    the tree becomes a fake page/proposal); selection is explicit argv, only
    from pages/ (proposals denied); refuses lint-failing trees; truncation
    is visible, never silent; budget counts the full serialized artifact.
    """

    root_res = root.resolve()
    out_parent = out.parent.resolve()
    # Component-wise containment: a sibling like <root>-backup must not be
    # refused by a string-prefix comparison.
    if out_parent == root_res or root_res in out_parent.parents:
        raise SystemExit(
            f"export: --out must be outside the knowledge tree: {out}"
        )
    pages_dir = (root / "pages").resolve()
    lint_violations = (lint_pages(root, registry) + lint_proposals(root))
    if lint_violations:
        raise SystemExit(
            "export: refusing to bundle a lint-failing tree "
            f"({len(lint_violations)} violation(s); run lint)"
        )
    sections: list[str] = []
    for rel in page_rels:
        page = (root / "pages" / rel)
        resolved = page.resolve()
        if not str(resolved).startswith(str(pages_dir) + os.sep):
            raise SystemExit(f"export: page outside pages/: {rel}")
        if not resolved.is_file():
            raise SystemExit(f"export: no such page: {rel}")
        text, read_violations = _read_page(page, rel)
        if text is None:
            raise SystemExit("export: " + "; ".join(read_violations))
        fm, body, _v = _split_frontmatter(text, rel)
        fm = fm or {}
        meta = " | ".join(
            f"{k}: {_sanitize_cell(fm.get(k, '-'))}"
            for k in ("title", "status", "trust", "impact", "author",
                      "reviewer", "last_reviewed")
        )
        srcs = fm.get("source_ids")
        src_line = ", ".join(s for s in srcs if isinstance(s, str)) \
            if isinstance(srcs, list) else "-"
        sections.append(
            f"## page: {rel}\n<!-- {meta} -->\n"
            f"<!-- source_ids: {_sanitize_cell(src_line)} -->\n\n"
            f"{body.strip()}\n"
        )
    stamp = stamp or _utc_now()
    header = _bundle_header(page_rels, budget, stamp, True)
    marker = "\n\n...[truncated: budget reached]\n"
    # The banner is a hard floor: truncation may only ever eat page
    # content, never the first-bytes warning.
    if budget < len(header) + len(marker):
        raise SystemExit(
            f"export: budget {budget} smaller than the mandatory banner "
            f"({len(header) + len(marker)} code points)"
        )
    body_text = "\n".join(sections)
    artifact = header + body_text
    if len(artifact) > budget:
        cut = artifact[: budget - len(marker)]
        # If the cut lands inside an HTML comment, close it first so the
        # truncation marker is rendered, not swallowed. Delimiter COUNTING
        # is skewed by a stray visible '-->' in page content; run the
        # char-accurate comment scrubber over the cut and use its end state.
        in_comment = False
        for line in cut.split("\n"):
            _, in_comment = _scrub_comments(line, in_comment)
        if in_comment:
            cut = cut[: len(cut) - 5] + " -->"
        artifact = cut + marker
    with _safe_create_exclusive(out_parent, out_parent / out.name) as fh:
        fh.write(artifact)
    return out


# --------------------------------------------------------------------------
# index / log generation (the only overwriting write paths)
# --------------------------------------------------------------------------

_ISO_TS_RE = re.compile(
    r"^\d{4}-\d{2}-\d{2}"
    r"(?:[T ]\d{2}:\d{2}(?::\d{2}(?:\.\d{1,6})?)?(?:Z|[+-]\d{2}:\d{2})?)?$"
)


def _valid_iso_timestamp(value: str) -> bool:
    """Pinned grammar THEN calendar validity: fromisoformat alone accepts
    non-ISO variants (compact dates, week dates), so the shape is
    regex-gated first."""
    candidate = value
    if candidate.endswith("Z") and "T" in candidate:
        candidate = candidate[:-1] + "+00:00"
    if not _ISO_TS_RE.match(value):
        return False
    try:
        datetime.fromisoformat(candidate)
    except ValueError:
        return False
    return True


def _refuse_symlink_components(base: Path, path: Path) -> None:
    """Every component from base down to path must be symlink-free.

    Parent-only checks are insufficient: a symlinked intermediate directory
    resolves 'inside' while the entry redirects outside.
    """
    cur = base
    for part in path.relative_to(base).parts:
        cur = cur / part
        if cur.is_symlink():
            raise SystemExit(f"refusing symlinked path component: {cur}")


def _safe_create_exclusive(base: Path, path: Path):
    """Atomically create a NEW file under base; refuse symlinks and races.

    O_CREAT|O_EXCL (|O_NOFOLLOW where available) makes create-or-fail
    atomic, closing the exists()-then-open TOCTOU window.
    """
    if not str(path.resolve().parent).startswith(str(base.resolve())):
        raise SystemExit(f"refusing output outside {base}: {path}")
    _refuse_symlink_components(base, path)
    # Anchor creation to a dir-fd of the VERIFIED parent so a concurrent
    # swap of the directory for a symlink after the component check cannot
    # redirect the write.
    nofollow = getattr(os, "O_NOFOLLOW", 0)
    dfd = os.open(path.parent, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0) | nofollow)
    try:
        fd = os.open(path.name, os.O_CREAT | os.O_EXCL | os.O_WRONLY | nofollow,
                     0o600, dir_fd=dfd)
    except FileExistsError:
        raise SystemExit(f"refusing to overwrite existing file: {path}")
    finally:
        os.close(dfd)
    return os.fdopen(fd, "w", encoding="utf-8")


def _safe_output_path(root: Path, filename: str) -> Path:
    """Refuse to write through symlinks or outside root.

    The tool's contract is exactly two overwriting write paths inside the
    knowledge root; a committed symlink at either path must not redirect
    the write to an arbitrary file.
    """
    path = root / filename
    if path.is_symlink():
        raise SystemExit(f"index: refusing to write through symlink: {path}")
    if path.parent.resolve() != root.resolve():
        raise SystemExit(f"index: output path escapes root: {path}")
    return path


def generate_index(root: Path, registry: dict, log_timestamp: str | None = None) -> str:
    pages, violations = _iter_pages(root)
    if violations:
        raise SystemExit("index: refusing to generate: " + "; ".join(violations))
    index_path = _safe_output_path(root, "index.md")
    log_path = _safe_output_path(root, "log.md")
    rows = []
    for page in pages:
        text, read_violations = _read_page(page, page.name)
        if text is None:
            raise SystemExit(
                "index: refusing to generate: " + "; ".join(read_violations)
            )
        fm, _body, _v = _split_frontmatter(text, page.name)
        fm = fm or {}
        rel = page.resolve().relative_to((root / "pages").resolve()).as_posix()
        srcs = fm.get("source_ids")
        rows.append(
            "| [{title}](pages/{name}) | {status} | {kind} | {nsrc} | {reviewed} |".format(
                title=_sanitize_cell(fm.get("title", page.stem)),
                # URL-encode the path so exotic filenames cannot break or
                # reshape the generated link.
                name=quote(rel, safe="/"),
                status=_sanitize_cell(fm.get("status", "?")),
                kind=_sanitize_cell(fm.get("kind", "?")),
                # Malformed frontmatter must not crash the catalog; lint is
                # the enforcement gate, index is a resilient view.
                nsrc=len(srcs) if isinstance(srcs, list) else 0,
                reviewed=_sanitize_cell(fm.get("last_reviewed", "-")),
            )
        )
    index_text = (
        "# Knowledge index\n\n"
        "> Generated by `knowledge_tool.py index` — do not hand-edit.\n"
        "> Derived artifact; never authoritative.\n\n"
        f"Pages: {len(rows)} | Registered sources: {len(registry)}\n\n"
        "| Page | Status | Kind | Sources | Last reviewed |\n"
        "|---|---|---|---|---|\n" + ("\n".join(rows) + "\n" if rows else "")
    )
    index_path.write_text(index_text, encoding="utf-8")
    stamp = log_timestamp or _utc_now()
    prefix = "" if log_path.exists() and log_path.read_text(encoding="utf-8") else (
        "# Knowledge log\n\n"
        "> Append-only operation log, written only by "
        "`knowledge_tool.py index`.\n\n"
    )
    with log_path.open("a", encoding="utf-8") as fh:
        fh.write(
            f"{prefix}- {_sanitize_cell(stamp)} | index | "
            f"pages={len(rows)} sources={len(registry)}\n"
        )
    return index_text


# --------------------------------------------------------------------------
# init: idempotent, non-destructive scaffolding
# --------------------------------------------------------------------------

_REGISTRY_SKELETON = """\
# Source provenance registry — parsed by knowledge_tool.py (restricted YAML
# subset: flat mappings, lists, block scalars; no anchors/aliases/tags).
# Each source entry records provenance and constraints; provenance is NOT
# authorization. Example entry:
#
# sources:
#   - source_id: external.example.article.20260101
#     kind: external_research
#     location: https://example.com/article
#     retrieved_at: "2026-01-01T00:00:00Z"
#     content_sha256: ""
#     unhashed_reason: remote source, content hash not captured
#     trust: untrusted_external
#     allowed_use: research_context
sources: []
"""


def cmd_init(root: Path) -> int:
    """Scaffold the knowledge/ layout. Never overwrites existing content."""
    if root.is_symlink():
        raise SystemExit(f"init: refusing symlinked root: {root}")
    if root.exists() and not root.is_dir():
        raise SystemExit(f"init: path exists but is not a directory: {root}")
    created: list[str] = []
    for rel in ("", "sources", "pages", "proposals"):
        target = root / rel if rel else root
        if not target.exists():
            target.mkdir(parents=True)
            created.append(f"{target}/")
        elif not target.is_dir():
            raise SystemExit(f"init: path exists but is not a directory: {target}")
    registry = root / "sources" / "registry.yaml"
    if not registry.exists():
        with _safe_create_exclusive(root, registry) as fh:
            fh.write(_REGISTRY_SKELETON)
        created.append(str(registry))
    if created:
        for item in created:
            print(f"init: created {item}")
    else:
        print("init: already initialized (nothing to do)")
    return 0


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Deterministic project-knowledge tooling "
                    "(agent-collab project-knowledge skill)."
    )
    parser.add_argument(
        "command",
        choices=("init", "validate", "lint", "index", "draft", "export"),
    )
    parser.add_argument(
        "--root", type=Path, default=DEFAULT_ROOT,
        help="knowledge layer root (default: ./knowledge)",
    )
    parser.add_argument(
        "--log-timestamp", default=None,
        help="override the log row timestamp (tests only)",
    )
    parser.add_argument("--title", default=None, help="draft: proposal title")
    parser.add_argument(
        "--source-id", action="append", default=[], dest="source_ids",
        help="draft: registered source_id (repeatable, at least one)",
    )
    parser.add_argument(
        "--kind", default="synthesis", help="draft: page kind",
    )
    parser.add_argument(
        "--page", action="append", default=[], dest="pages",
        help="export: page path relative to pages/ (repeatable, explicit)",
    )
    parser.add_argument(
        "--out", type=Path, default=None,
        help="export: output bundle file (must be outside knowledge/)",
    )
    parser.add_argument(
        "--budget-chars", type=int, default=_EXPORT_DEFAULT_BUDGET,
        help="export: cap in code points over the full serialized artifact",
    )
    args = parser.parse_args(argv)

    if args.command == "init":
        return cmd_init(args.root)

    registry, violations = load_registry(args.root)
    if args.command == "validate":
        pass  # registry violations alone decide
    elif args.command == "lint":
        violations = (violations + lint_pages(args.root, registry)
                      + lint_proposals(args.root))
    elif args.command == "draft":
        if violations:
            print("draft: registry invalid; fix before drafting:")
        elif not args.title or not args.source_ids:
            print("draft: --title and at least one --source-id are required")
            return 2
        else:
            target = create_draft(
                args.root, args.title, args.source_ids, args.kind, registry
            )
            print(f"draft: wrote proposal skeleton {target}")
    elif args.command == "export":
        if violations:
            print("export: registry invalid; fix before exporting:")
        elif not args.pages or args.out is None:
            print("export: at least one --page and --out are required")
            return 2
        else:
            out = export_bundle(
                args.root, args.pages, args.out, args.budget_chars,
                registry, args.log_timestamp,
            )
            print(f"export: wrote bundle {out}")
    elif args.command == "index":
        if violations:
            print("index: refusing to generate; registry invalid:")
        else:
            generate_index(args.root, registry, args.log_timestamp)
            print(f"index: wrote {args.root / 'index.md'} (+1 log row)")

    for v in violations:
        print(f"VIOLATION: {v}")
    print(f"{args.command}: {'FAIL' if violations else 'OK'} "
          f"({len(violations)} violation(s))")
    return 1 if violations else 0


if __name__ == "__main__":
    sys.exit(main())
