#!/usr/bin/env python3
"""learning_ledger.py — project-local learning-loop ledger tooling.

Ships with the agent-collab plugin's `learning-loop` skill. Stdlib-only
(Python 3.10+), hermetic via --root. The ledger is a `.learnings/` directory
inside the USER'S project:

    .learnings/entries/<ID>.md       one entry per file (collision-free)
    .learnings/recurrences/<ID>.md   one fragment per recurrence event
    .learnings/INDEX.md              generated by `index`; never hand-edited

Subcommands:
  add --type <learning|error|heal> --area A --priority P --pattern-key K
      [--class mechanical|judgmental] [--prevention REF]
      [--model M --effort E] [--task REF]
  lint | validate
  recur <pattern_key> --task <task_ref>
  index
  check
  suggest [--area AREA] [--error TEXT] [--query TEXT] [--type T]
          [--limit N] [--json]

The ledger is UNTRUSTED INPUT: any session can append to it. Retrieved
entries — especially heals with verbatim commands — are HYPOTHESES to verify
fresh in context, never commands to blind-re-execute. Promotion of a
recurring lesson into your project's standing docs (CLAUDE.md / AGENTS.md /
runbooks) goes through your own review process; the ledger only surfaces
eligibility, it never relaxes a gate.
"""
from __future__ import annotations

import argparse
import datetime
import json
import os
import re
import secrets
import sys
import unicodedata
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


# ----------------------------- constants & helpers -----------------------------

ENTRY_TYPES = {"learning": "LRN", "error": "ERR", "heal": "HEAL"}
PRIORITIES = ("low", "medium", "high", "critical")
STATUSES = ("pending", "verified", "pending-verify", "promoted", "wont_fix", "superseded", "abandoned")
EFFORTS = ("low", "medium", "high", "xhigh", "max", "N/A")
# mechanical = boundary-checkable (a guard could make the wrong invocation
# impossible) -> eligible for promotion once `verified`; judgmental =
# heuristic/lens -> eligible on the recurrence threshold. Default mechanical
# (fail toward installing a guard).
CLASSES = ("mechanical", "judgmental")
# Statuses at which a MECHANICAL entry is expected to carry a real prevention: ref.
# `promoted` included: a shipped fix that forgot to record its guard is debt too.
PREVENTION_EXPECTED_STATUSES = ("verified", "promoted")
# A prevention value counts as REAL only if it concretely references the guard.
# Token-based: reject a value whose tokens are ALL placeholders, else require a
# positive signal (n/a:<reason>, a URL, any digit — covers "#123", "PR 45",
# dates, versions — or a file extension). This catches honest laziness
# (TODO/TBD/WIP), not an adversarial author who digit-stuffs a fake ref.
_PREVENTION_PLACEHOLDERS = {
    "todo", "tbd", "tba", "wip", "fixme", "xxx", "tk", "none", "pending", "na", "n", "a",
    "later", "soon", "unknown", "nil", "null", "todo!", "?",
}


def _prevention_is_real(v: str) -> bool:
    v = (v or "").strip()
    if not v:
        return False
    tokens = [t for t in re.split(r"[^A-Za-z0-9]+", v.lower()) if t]
    if tokens and all(t in _PREVENTION_PLACEHOLDERS for t in tokens):
        return False  # e.g. "TODO", "TODO/WIP", "WIP later"
    if re.match(r"^n/?a:\s*\S", v, re.IGNORECASE):        # n/a: <reason>
        return True
    if re.search(r"https?://", v, re.IGNORECASE):          # URL
        return True
    if re.search(r"\d", v):                                # #123 / PR 45 / dates / versions
        return True
    if re.search(r"\.\w{1,5}(?:\b|/|$)", v):               # a file extension (.py/.md/.sh)
        return True
    return False


ENTRY_ID_RE = re.compile(r"^(LRN|ERR|HEAL)-\d{8}-\d{6}-[a-z]+-[0-9a-f]{4}$")
RECUR_ID_RE = re.compile(r"^REC-\d{8}-\d{6}-[a-z]+-[0-9a-f]{4}$")
PATTERN_KEY_RE = re.compile(r"^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*$")
# Agent names embed into entry IDs, so they are restricted to lowercase
# letters (the ID grammar's `-[a-z]+-` segment).
AGENT_NAME_RE = re.compile(r"^[a-z]{1,20}$")

IMP_RE = re.compile(r"^\s*(run|execute|delete|curl|rm|sudo|eval)\b", re.IGNORECASE)

FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n(.*)\Z", re.DOTALL)


def _get_ledger_root(root_arg: Optional[str]) -> Path:
    if root_arg:
        return Path(root_arg).resolve()
    return (Path.cwd() / ".learnings").resolve()


def _detect_agent() -> str:
    """Best-effort agent attribution for provenance.

    An explicit, validated AGENT_NAME is AUTHORITATIVE — a session that
    declares its identity is never overridden by an inherited env var.
    Per-session host signals come next; the neutral fallback is "agent".
    """
    env = os.environ
    ag = (env.get("AGENT_NAME") or "").strip().lower()
    if AGENT_NAME_RE.match(ag):
        return ag
    if env.get("CLAUDE_CODE_SESSION_ID") or env.get("CLAUDE_SESSION_ID"):
        return "claude"
    if env.get("CODEX_THREAD_ID") or env.get("CODEX_SESSION_ID"):
        return "codex"
    return "agent"


def _get_session_id() -> str:
    env = os.environ
    return (
        env.get("CLAUDE_CODE_SESSION_ID")
        or env.get("CLAUDE_SESSION_ID")
        or env.get("CODEX_THREAD_ID")
        or env.get("CODEX_SESSION_ID")
        or env.get("CONVERSATION_ID")
        or ""
    )


def _now_utc() -> Tuple[str, str, str]:
    """Return (YYYYMMDD, HHMMSS, ISO8601Z) for UTC now."""
    dt = datetime.datetime.now(datetime.timezone.utc)
    return dt.strftime("%Y%m%d"), dt.strftime("%H%M%S"), dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def _parse_iso(ts: str) -> datetime.datetime:
    ts = (ts or "").strip()
    epoch = datetime.datetime.fromtimestamp(0, tz=datetime.timezone.utc)
    if not ts:
        return epoch
    if ts.endswith("Z"):
        ts = ts[:-1] + "+00:00"
    try:
        dt = datetime.datetime.fromisoformat(ts)
    except Exception:
        return epoch
    # A tz-NAIVE timestamp (manual edit, no offset) must not raise when
    # compared to a tz-aware cutoff. Always return tz-aware (naive => UTC).
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=datetime.timezone.utc)
    return dt


def _is_valid_pattern_key(pk: str) -> bool:
    return bool(PATTERN_KEY_RE.match(pk or ""))


def _is_valid_task_ref(ref: str) -> bool:
    """Any non-empty external task reference is accepted: an issue/PR number
    ("#123"), a ticket id, a URL, or a short descriptive anchor."""
    return bool((ref or "").strip())


def _canonicalize_task_ref(ref: str) -> str:
    """Canonicalize a task_ref so equivalent forms dedup/count as ONE: a
    "#NNN" anchor strips leading zeros (#001 -> #1); other forms are
    returned stripped."""
    ref = (ref or "").strip()
    m = re.match(r"^#0*(\d+)$", ref)
    if m:
        return "#" + m.group(1)
    return ref


def _section_text(body: str, header: str) -> str:
    """Return the text under a '## <header>' section (until the next '## '
    or EOF), stripped. Used to assert a verified heal carries non-empty
    proof content."""
    pat = re.compile(
        r"^[ \t]*##[ \t]*" + re.escape(header) + r"\b[^\n]*\n(.*?)(?=^[ \t]*##[ \t]|\Z)",
        re.MULTILINE | re.DOTALL,
    )
    m = pat.search(body)
    return (m.group(1).strip() if m else "")


def _needs_quote(s: str) -> bool:
    if not s:
        return True
    # allow ISO timestamps, ids, paths, : - @ + etc bare (quote only when
    # special like # or spaces)
    if re.match(r"^[A-Za-z0-9_./:@+-]+$", s) and s[0] not in ("#", "'", '"'):
        return False
    return True


def _format_simple_value(v: Any) -> str:
    # Lists and dicts -> compact JSON. A string that needs quoting ->
    # json.dumps too (double-quoted, properly escaping backslashes /
    # newlines / quotes). Bare-safe scalars stay readable; None -> "".
    if isinstance(v, (list, dict)):
        return json.dumps(v, ensure_ascii=False, sort_keys=isinstance(v, dict))
    if v is None:
        return ""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v)
    if _needs_quote(s):
        return json.dumps(s, ensure_ascii=False)
    return s


def _serialize_frontmatter(fm: Dict[str, Any], key_order: Optional[List[str]] = None) -> str:
    lines = ["---"]
    if key_order is None:
        key_order = ["id", "type", "created", "agent", "model", "effort", "area", "priority",
                     "status", "pattern_key", "class", "prevention", "provenance",
                     "related_files", "see_also"]
    seen = set()
    for k in key_order:
        if k in fm:
            lines.append(f"{k}: {_format_simple_value(fm[k])}")
            seen.add(k)
    for k, v in fm.items():
        if k not in seen:
            lines.append(f"{k}: {_format_simple_value(v)}")
    lines.append("---")
    return "\n".join(lines) + "\n"


def _parse_simple_value(s: str) -> Any:
    s = (s or "").strip()
    if not s:
        return ""
    # JSON value (the format _format_simple_value writes): "..." / [...] /
    # {...} — robust round-trip including escapes.
    if s[0] in '"[{':
        try:
            return json.loads(s)
        except ValueError:
            # Lenient fallback for a hand-written single-quoted list/dict/string.
            try:
                import ast
                return ast.literal_eval(s)
            except Exception:
                pass
    # Hand-written single-quoted scalar: strip the quotes and unescape \'.
    if len(s) >= 2 and s[0] == "'" and s[-1] == "'":
        return s[1:-1].replace("\\'", "'")
    return s


def parse_frontmatter(text: str) -> Tuple[Dict[str, Any], str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        # fallback: try to find first --- ... ---
        if not text.startswith("---\n"):
            raise ValueError("no frontmatter")
        try:
            end = text.index("\n---\n", 4)
        except ValueError:
            raise ValueError("no frontmatter end")
        raw = text[4:end]
        body = text[end + 5:]
    else:
        raw, body = m.group(1), m.group(2)
    fields: Dict[str, Any] = {}
    for line in raw.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        k = k.strip()
        if not k:
            continue
        fields[k] = _parse_simple_value(v)
    return fields, body.strip()


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)


def _read_text_safe(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8")
    except Exception:
        return ""


# ----------------------------- add -----------------------------

def cmd_add(args: argparse.Namespace) -> int:
    root = _get_ledger_root(args.root)
    entries_dir = root / "entries"
    entries_dir.mkdir(parents=True, exist_ok=True)

    typ = args.type
    if typ not in ENTRY_TYPES:
        print(f"error: invalid --type {typ}", file=sys.stderr)
        return 1
    prefix = ENTRY_TYPES[typ]

    area = args.area.strip()
    priority = args.priority
    if priority not in PRIORITIES:
        print(f"error: invalid --priority {priority}", file=sys.stderr)
        return 1

    pk = args.pattern_key.strip()
    if not _is_valid_pattern_key(pk):
        print(f"error: invalid --pattern-key {pk} (must be lower.snake.case)", file=sys.stderr)
        return 1

    agent = _detect_agent()
    datep, timep, created = _now_utc()

    model = args.model if args.model is not None else "N/A"
    effort = args.effort if args.effort is not None else "N/A"
    if effort not in EFFORTS:
        effort = "N/A"

    sess = _get_session_id()

    # provenance.task_ref: OPTIONAL-BUT-WARNED. Branch order is load-bearing:
    # an explicit --task (even "") signals the user INTENDED an anchor, so a
    # blank value is a HARD ERROR, never the soft path; only a truly OMITTED
    # --task (None) takes the capture-first advisory (the lesson often
    # predates its task anchor).
    prov: Dict[str, Any] = {"session_id": sess}
    if args.task is None:
        print("warning: entry born without provenance.task_ref — pass --task <ref> "
              "(issue/PR number, ticket id, URL, or a short descriptive anchor) "
              "to anchor it to a task", file=sys.stderr)
    else:
        tref = args.task.strip()
        if not tref or not _is_valid_task_ref(tref):
            print(f"error: invalid --task {args.task!r} (must be a non-empty "
                  f"external task reference)", file=sys.stderr)
            return 1
        prov["task_ref"] = _canonicalize_task_ref(tref)  # #01 -> #1, matching recur

    # generate unique ID (re-roll rand4 on collision)
    iid = ""
    for _ in range(100):  # safety
        rand = secrets.token_hex(2)
        cand = f"{prefix}-{datep}-{timep}-{agent}-{rand}"
        if not (entries_dir / f"{cand}.md").exists():
            iid = cand
            break
    if not iid:
        print("error: failed to allocate unique entry id", file=sys.stderr)
        return 1

    fm: Dict[str, Any] = {
        "id": iid,
        "type": typ,
        "created": created,
        "agent": agent,
        "model": model,
        "effort": effort,
        "area": area,
        "priority": priority,
        "status": "pending",
        "pattern_key": pk,
        "class": getattr(args, "klass", "mechanical") or "mechanical",
        "prevention": getattr(args, "prevention", "") or "",
        "provenance": prov,
        "related_files": [],
        "see_also": [],
    }

    body_parts = [
        "## Context / Failure",
        "",
        "",
        "## Diagnosis / Insight",
        "",
        "",
        "## Fix / Recommendation",
        "",
    ]
    if typ == "heal":
        body_parts.extend([
            "",
            "## Verification",
            "",
            "",
            "## Rollback note",
            "",
        ])

    content = _serialize_frontmatter(fm) + "\n" + "\n".join(body_parts) + "\n"
    path = entries_dir / f"{iid}.md"
    _atomic_write(path, content)
    print(str(path))
    return 0


# ----------------------------- lint / validate -----------------------------

def _lint_one(path: Path, is_entry: bool) -> Tuple[List[str], List[str]]:
    errors: List[str] = []
    advisories: List[str] = []
    stem = path.stem
    text = _read_text_safe(path)
    if not text:
        errors.append(f"{stem}: unreadable")
        return errors, advisories
    try:
        fm, body = parse_frontmatter(text)
    except Exception as e:
        errors.append(f"{stem}: bad frontmatter: {e}")
        return errors, advisories

    # id matches stem
    if fm.get("id") != stem:
        errors.append(f"{stem}: id frontmatter does not match filename stem")

    # required keys
    if is_entry:
        required = ["id", "type", "created", "agent", "model", "effort", "area", "priority",
                    "status", "pattern_key", "provenance", "related_files", "see_also"]
        id_re = ENTRY_ID_RE
        type_ok = fm.get("type") in ("learning", "error", "heal")
    else:
        required = ["id", "pattern_key", "created", "task_ref", "agent"]
        id_re = RECUR_ID_RE
        type_ok = True

    missing = [k for k in required if k not in fm]
    if missing:
        errors.append(f"{stem}: missing required keys: {missing}")

    # Every REQUIRED SCALAR field must be non-blank: a present-but-blank
    # value satisfies the key-presence check above but would otherwise skip
    # the per-field enum/format validation below and corrupt derived
    # provenance + the recurrence_log audit trail.
    _nonblank_scalars = ("id", "type", "created", "agent", "model", "effort", "area",
                         "priority", "status", "pattern_key", "task_ref")
    for k in _nonblank_scalars:
        if k in required and k in fm and not str(fm.get(k, "")).strip():
            errors.append(f"{stem}: required field {k!r} must not be blank")

    if "id" in fm and not id_re.match(str(fm.get("id"))):
        errors.append(f"{stem}: id does not match ID regex")

    if is_entry and not type_ok:
        errors.append(f"{stem}: invalid type")

    # class + prevention-debt surface.
    if is_entry:
        _klass = str(fm.get("class", "")).strip()
        _status = str(fm.get("status", "")).strip()
        _prevention = str(fm.get("prevention", "")).strip()
        if _klass and _klass not in CLASSES:
            errors.append(f"{stem}: invalid class {_klass!r} (must be mechanical|judgmental)")
        if _status in PREVENTION_EXPECTED_STATUSES and not _klass:
            advisories.append(f"{stem}: advisory: {_status} entry has no class: — set mechanical|judgmental "
                              f"(treated as mechanical for the prevention-debt surface until set)")
        # A verified/promoted MECHANICAL fix with no REAL prevention: ref is a
        # known-but-uninstalled guard = tracked debt. A bare placeholder
        # ("TODO") does NOT satisfy it. A MISSING class defaults to mechanical
        # here: a classless verified entry must not dodge the debt surface.
        if (_status in PREVENTION_EXPECTED_STATUSES and _klass in ("", "mechanical")
                and not _prevention_is_real(_prevention)):
            advisories.append(f"{stem}: PREVENTION-DEBT: {_status} mechanical entry has no real "
                              f"prevention: ref (guard PR/path/URL or 'n/a: <reason>') — "
                              f"the fix is known but not installed")

        # provenance.task_ref: validate when present; surface ABSENCE as an
        # ADVISORY, never an error, so a hard presence-gate does not
        # retroactively fail `check` for every existing task_ref-less entry.
        _prov = fm.get("provenance")
        if isinstance(_prov, dict):
            if "task_ref" not in _prov:
                advisories.append(f"{stem}: advisory: provenance has no task_ref — anchor the entry to a "
                                  f"task via `add --task <ref>`")
            else:
                _raw_tr = _prov.get("task_ref")
                if not isinstance(_raw_tr, str) or not _raw_tr.strip():
                    errors.append(f"{stem}: provenance.task_ref must be a nonblank string anchor "
                                  f"(got {type(_raw_tr).__name__}: {_raw_tr!r}) — remove the key or set it to "
                                  f"a non-empty external task reference")

    ag = str(fm.get("agent", ""))
    if ag and not AGENT_NAME_RE.match(ag):
        errors.append(f"{stem}: invalid agent {ag} (must be 1-20 lowercase letters)")

    # created must be a FULL ISO-8601 UTC timestamp — date + time. A
    # malformed value parses to the epoch sentinel; a DATE-ONLY value parses
    # as midnight and would otherwise pass, but it drops the time component
    # the sub-24h echo-chamber lock needs to be enforceable.
    cr_raw = str(fm.get("created", "")).strip()
    if "created" in fm:
        epoch = datetime.datetime.fromtimestamp(0, tz=datetime.timezone.utc)
        if not cr_raw or _parse_iso(cr_raw) == epoch or not re.match(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}", cr_raw):
            errors.append(f"{stem}: blank/malformed/incomplete created {cr_raw!r} (need a full ISO-8601 UTC timestamp with time, e.g. 2026-06-24T00:00:00Z)")

    pri = str(fm.get("priority", ""))
    if is_entry and pri and pri not in PRIORITIES:
        errors.append(f"{stem}: invalid priority {pri}")

    st = str(fm.get("status", ""))
    if is_entry and st and st not in STATUSES:
        errors.append(f"{stem}: invalid status {st}")

    eff = str(fm.get("effort", ""))
    if is_entry and eff and eff not in EFFORTS:
        errors.append(f"{stem}: invalid effort {eff}")

    pk = str(fm.get("pattern_key", ""))
    if not _is_valid_pattern_key(pk):
        errors.append(f"{stem}: invalid pattern_key (not lower.snake.case)")

    # advisory imperative outside Fix for entries
    if is_entry:
        in_fix = False
        for line in body.splitlines():
            if re.match(r"^\s*##\s*Fix\s*/\s*Recommendation", line, re.IGNORECASE):
                in_fix = True
                continue
            if re.match(r"^\s*##\s", line):
                in_fix = False
            if not in_fix and IMP_RE.search(line or ""):
                advisories.append(f"{stem}: advisory: imperative instruction outside ## Fix / Recommendation: {line.strip()[:80]}")

    # Heal proof sections are MANDATORY: a heal must carry re-run
    # Verification + a Rollback note before it can be reused as a recovery
    # hypothesis.
    if is_entry and fm.get("type") == "heal":
        has_verif = bool(re.search(r"^\s*##\s*Verification\b", body, re.MULTILINE | re.IGNORECASE))
        has_rb = bool(re.search(r"^\s*##\s*Rollback note\b", body, re.MULTILINE | re.IGNORECASE))
        if not has_verif:
            errors.append(f"{stem}: heal entry missing mandatory '## Verification' section")
        if not has_rb:
            errors.append(f"{stem}: heal entry missing mandatory '## Rollback note' section")
        # A VERIFIED heal must carry NON-EMPTY proof, not just empty
        # headings — a verified heal is reused as a recovery hypothesis, so
        # it needs real re-run proof + rollback detail. A pending /
        # pending-verify heal may still have the skeleton sections empty.
        if str(fm.get("status", "")) == "verified":
            if has_verif and not _section_text(body, "Verification"):
                errors.append(f"{stem}: verified heal has an empty '## Verification' section (needs re-run proof)")
            if has_rb and not _section_text(body, "Rollback note"):
                errors.append(f"{stem}: verified heal has an empty '## Rollback note' section")

    return errors, advisories


def _lint_recurrence_cross_fragment(rec_dir: Path) -> List[str]:
    """Cross-fragment recurrence integrity: enforce in lint/check the SAME
    echo-chamber invariants `recur` enforces at write time, so a
    hand-written or merge-conflicted fragment cannot bypass them and inflate
    recurrence counts —
      1. no duplicate (pattern_key, canonical task_ref); and
      2. no two same-agent, same-pattern_key recurrences within 24h."""
    errors: List[str] = []
    if not rec_dir.is_dir():
        return errors
    frags: List[Tuple[str, str, str, datetime.datetime, str]] = []  # pk, canon_tr, agent, created, stem
    for p in sorted(rec_dir.glob("*.md")):
        if p.name.startswith("."):
            continue
        try:
            fm, _ = parse_frontmatter(_read_text_safe(p))
            pk = str(fm.get("pattern_key") or "").strip()
            tr = _canonicalize_task_ref(str(fm.get("task_ref") or ""))
            agent = str(fm.get("agent") or "").strip()
            created = _parse_iso(str(fm.get("created") or ""))
            if pk and tr and _is_valid_task_ref(tr):
                frags.append((pk, tr, agent, created, p.stem))
        except Exception:
            pass
    # 1. duplicate (pattern_key, canonical task_ref)
    seen: Dict[Tuple[str, str], str] = {}
    for pk, tr, _agent, _created, stem in frags:
        key = (pk, tr)
        if key in seen:
            errors.append(f"{stem}: duplicate recurrence for pattern_key={pk} task_ref={tr} (also recorded in {seen[key]})")
        else:
            seen[key] = stem
    # 2. same-agent, same-pattern_key within 24h (sorted by created →
    # compare consecutive per group)
    day = 24 * 3600
    last: Dict[Tuple[str, str], Tuple[datetime.datetime, str]] = {}
    for pk, _tr, agent, created, stem in sorted(frags, key=lambda x: (x[0], x[2], x[3], x[4])):
        if not agent:
            continue
        k = (pk, agent)
        prev = last.get(k)
        if prev is not None and (created - prev[0]).total_seconds() < day:
            errors.append(f"{stem}: same-agent ({agent}) recurrence for pattern_key={pk} within 24h of {prev[1]} (echo-chamber 24h lock)")
        last[k] = (created, stem)
    return errors


def cmd_lint(args: argparse.Namespace) -> int:
    root = _get_ledger_root(args.root)
    all_errors: List[str] = []
    all_advisories: List[str] = []

    entries_dir = root / "entries"
    if entries_dir.is_dir():
        for p in sorted(entries_dir.glob("*.md")):
            if p.name.startswith("."):
                continue
            e, a = _lint_one(p, is_entry=True)
            all_errors.extend(e)
            all_advisories.extend(a)

    rec_dir = root / "recurrences"
    if rec_dir.is_dir():
        for p in sorted(rec_dir.glob("*.md")):
            if p.name.startswith("."):
                continue
            e, a = _lint_one(p, is_entry=False)
            all_errors.extend(e)
            all_advisories.extend(a)

    # cross-fragment recurrence integrity (dedup + 24h same-agent lock)
    all_errors.extend(_lint_recurrence_cross_fragment(root / "recurrences"))

    for msg in all_errors:
        print(f"error: {msg}", file=sys.stderr)
    for msg in all_advisories:
        print(f"warning: {msg}", file=sys.stderr)

    if all_errors:
        return 1
    return 0


# ----------------------------- recur -----------------------------

def cmd_recur(args: argparse.Namespace) -> int:
    root = _get_ledger_root(args.root)
    rec_dir = root / "recurrences"
    rec_dir.mkdir(parents=True, exist_ok=True)

    pk = args.pattern_key.strip()
    if not _is_valid_pattern_key(pk):
        print(f"error: invalid pattern_key {pk}", file=sys.stderr)
        return 1

    task_ref = args.task.strip()
    if not _is_valid_task_ref(task_ref):
        print(f"error: invalid --task {task_ref!r} (must be a non-empty external task reference)", file=sys.stderr)
        return 1
    # Canonicalize so #1 / #01 / #001 dedup + count as ONE.
    task_ref = _canonicalize_task_ref(task_ref)

    agent = _detect_agent()
    datep, timep, created = _now_utc()

    # dedup exact (pk, task_ref) — compare on the CANONICAL form so a stored
    # #01 collides with #1
    for f in rec_dir.glob("*.md"):
        try:
            fm, _ = parse_frontmatter(_read_text_safe(f))
            if fm.get("pattern_key") == pk and _canonicalize_task_ref(str(fm.get("task_ref", ""))) == task_ref:
                print(f"error: duplicate recurrence already recorded for pattern_key={pk} task_ref={task_ref}", file=sys.stderr)
                return 1
        except Exception:
            pass

    # 24h same-agent lock. NOTE: the dedup + 24h checks are a best-effort
    # echo-chamber defense with a benign TOCTOU window (two concurrent
    # same-agent processes could each pass the check and both write, adding
    # at most one extra recurrence). ACCEPTED — the recur locks are
    # advisory; the AUTHORITATIVE gate is your own review on promotion,
    # which a stray extra fragment cannot bypass. File-locking is
    # over-engineering for an inert, low-concurrency tool.
    now = datetime.datetime.now(datetime.timezone.utc)
    cutoff = now - datetime.timedelta(hours=24)
    epoch = datetime.datetime.fromtimestamp(0, tz=datetime.timezone.utc)
    for f in rec_dir.glob("*.md"):
        try:
            fm, _ = parse_frontmatter(_read_text_safe(f))
            if (fm.get("pattern_key") == pk and fm.get("agent") == agent):
                raw_created = str(fm.get("created", "")).strip()
                cr = _parse_iso(raw_created)
                # FAIL-SAFE: a malformed/missing `created` parses to the
                # epoch sentinel and would otherwise look "old", letting a
                # hand-edited fragment bypass the 24h echo-chamber lock.
                # Treat an unparseable created as RECENT (block), never old.
                # (lint separately rejects such a fragment.)
                malformed = (cr == epoch)
                if malformed or cr >= cutoff:
                    why = f"fragment {f.name} has an unparseable created — fail-safe block" if malformed else "already exists"
                    print(f"error: sub-24h same-agent ({agent}) recurrence for pattern_key={pk} ({why})", file=sys.stderr)
                    return 1
        except Exception:
            pass

    # allocate unique recur id
    rid = ""
    for _ in range(100):
        rand = secrets.token_hex(2)
        cand = f"REC-{datep}-{timep}-{agent}-{rand}"
        if not (rec_dir / f"{cand}.md").exists():
            rid = cand
            break
    if not rid:
        print("error: failed to allocate unique recurrence id", file=sys.stderr)
        return 1

    fm: Dict[str, Any] = {
        "id": rid,
        "pattern_key": pk,
        "created": created,
        "task_ref": task_ref,
        "agent": agent,
    }
    content = _serialize_frontmatter(fm, key_order=["id", "pattern_key", "created", "task_ref", "agent"]) + "\n"
    path = rec_dir / f"{rid}.md"
    _atomic_write(path, content)
    print(str(path))
    return 0


# ----------------------------- index -----------------------------

def _generate_index_content(root: Path) -> str:
    entries_dir = root / "entries"
    rec_dir = root / "recurrences"

    entries_by_pk: Dict[str, List[str]] = {}
    prevention_debt: List[Tuple[str, str]] = []
    for p in entries_dir.glob("*.md") if entries_dir.is_dir() else []:
        if p.name.startswith("."):
            continue
        try:
            fm, _ = parse_frontmatter(_read_text_safe(p))
            pk = str(fm.get("pattern_key") or "").strip()
            iid = str(fm.get("id") or p.stem)
            if pk:  # skip a malformed/empty pattern_key
                entries_by_pk.setdefault(pk, []).append(iid)
                # A verified MECHANICAL entry with no prevention: is tracked
                # debt (a known-but-uninstalled guard). Surface it in the
                # INDEX. Missing class defaults to mechanical.
                if (str(fm.get("status") or "").strip() in PREVENTION_EXPECTED_STATUSES
                        and str(fm.get("class") or "").strip() in ("", "mechanical")
                        and not _prevention_is_real(str(fm.get("prevention") or ""))):
                    prevention_debt.append((pk, iid))
        except Exception:
            pass

    # INDEX counts ALL distinct task_refs per pattern_key — DETERMINISTIC
    # from the tree (no wall-clock window, so regenerating later on an
    # unchanged tree is byte-identical). Any sliding-window promotion-
    # eligibility policy is applied by your own review process, NOT here.
    rec_by_pk: Dict[str, set] = {}            # distinct canonical task_refs -> recurrence_count
    log_by_pk: Dict[str, List[Tuple[str, str, str, str]]] = {}  # per-recurrence -> recurrence_log
    for p in rec_dir.glob("*.md") if rec_dir.is_dir() else []:
        if p.name.startswith("."):
            continue
        try:
            fm, _ = parse_frontmatter(_read_text_safe(p))
            pk = str(fm.get("pattern_key") or "").strip()
            # Canonicalize (#01 -> #1) so leading-zero refs collapse to one
            # distinct count.
            tr = _canonicalize_task_ref(str(fm.get("task_ref") or ""))
            if pk and tr and _is_valid_task_ref(tr):
                rec_by_pk.setdefault(pk, set()).add(tr)
                # recurrence_log: keep each counted recurrence's
                # created/task_ref/agent so a reviewer can audit the
                # recurrence spread. DETERMINISTIC — sorted below.
                created = str(fm.get("created") or "").strip()
                agent = str(fm.get("agent") or "").strip()
                rid = str(fm.get("id") or p.stem).strip()
                log_by_pk.setdefault(pk, []).append((created, tr, agent, rid))
        except Exception:
            pass

    for pk in entries_by_pk:
        entries_by_pk[pk] = sorted(set(entries_by_pk[pk]))

    all_pks = sorted(set(list(entries_by_pk.keys()) + list(rec_by_pk.keys())))

    lines: List[str] = [
        "# Learning Ledger Index",
        "",
        "Generated by `learning_ledger.py index` — do not hand-edit.",
        "",
    ]
    for pk in all_pks:
        lines.append(f"## {pk}")
        count = len(rec_by_pk.get(pk, set()))
        lines.append(f"recurrence_count: {count}")
        lines.append("")
        ents = entries_by_pk.get(pk, [])
        if ents:
            lines.append("Entries:")
            for e in ents:
                lines.append(f"- {e}")
            lines.append("")
        # recurrence_log — ONE line per CANONICAL task_ref (created |
        # task_ref | agent | id), sorted for deterministic output. Deduped
        # by canonical ref so it matches recurrence_count exactly:
        # duplicate fragments (#1 and #001 from a hand-edit / merge
        # conflict) collapse to the earliest-created row.
        log = sorted(log_by_pk.get(pk, []))
        if log:
            lines.append("recurrence_log:")
            seen_refs: set = set()
            for created, tr, agent, rid in log:
                if tr in seen_refs:
                    continue
                seen_refs.add(tr)
                lines.append(f"- {created} | {tr} | {agent} | {rid}")
            lines.append("")
    if prevention_debt:
        lines.append("## Prevention debt")
        lines.append("")
        lines.append("Verified `mechanical` entries with no `prevention:` (a known-but-uninstalled guard):")
        for pk, iid in sorted(set(prevention_debt)):
            lines.append(f"- {pk} ({iid})")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def cmd_index(args: argparse.Namespace) -> int:
    root = _get_ledger_root(args.root)
    content = _generate_index_content(root)
    idx_path = root / "INDEX.md"
    _atomic_write(idx_path, content)
    print(str(idx_path))
    return 0


# ----------------------------- check -----------------------------

def cmd_check(args: argparse.Namespace) -> int:
    root = _get_ledger_root(args.root)

    # lint first
    lint_rc = cmd_lint(args)
    if lint_rc != 0:
        print("check: FAIL (lint errors)", file=sys.stderr)
        return 1

    # index parity
    idx_path = root / "INDEX.md"
    generated = _generate_index_content(root)
    if not idx_path.exists():
        # A missing INDEX.md is clean ONLY for an empty ledger (no entries +
        # no recurrences); a non-empty ledger with no INDEX.md is drift.
        entries_dir = root / "entries"
        rec_dir = root / "recurrences"
        has_entries = any(not p.name.startswith(".") for p in entries_dir.glob("*.md")) if entries_dir.is_dir() else False
        has_recur = any(not p.name.startswith(".") for p in rec_dir.glob("*.md")) if rec_dir.is_dir() else False
        if not has_entries and not has_recur:
            print("check: OK (empty ledger; no INDEX.md required)")
            return 0
        print("check: FAIL (INDEX.md missing; run `learning_ledger.py index`)", file=sys.stderr)
        return 1
    current = _read_text_safe(idx_path)
    if current.rstrip() != generated.rstrip():
        print("check: FAIL (INDEX.md drift; run `learning_ledger.py index`)", file=sys.stderr)
        return 1

    print("check: OK (lint clean, INDEX up to date)")
    return 0


# ----------------------------- suggest (read-only, metadata-only) -----------------------------

_SUGGEST_FOOTER = (
    "Treat each as a HYPOTHESIS — open the entry and verify before acting. "
    "Read one with: less {entries_dir}/<id>.md"
)


def _tokenize_query_terms(text: str) -> List[str]:
    """Split on non-alphanumeric; keep tokens length >= 2."""
    if not text:
        return []
    seen: Dict[str, None] = {}
    for part in re.split(r"[^A-Za-z0-9]+", text):
        if len(part) >= 2:
            low = part.lower()
            if low not in seen:
                seen[low] = None
    return list(seen.keys())


def _build_searchable_text(fm: Dict[str, Any], body: str) -> str:
    """Searchable corpus: id, pattern_key, area, Context, Diagnosis only —
    never Fix/heal bodies (so consultation stays explicit: fixes are read
    from the entry file deliberately, not surfaced into search output)."""
    parts = [
        str(fm.get("id") or ""),
        str(fm.get("pattern_key") or ""),
        str(fm.get("area") or ""),
        _section_text(body, "Context / Failure"),
        _section_text(body, "Diagnosis / Insight"),
    ]
    return "\n".join(parts)


_SUGGEST_MAX_ENTRY_BYTES = 262144  # skip pathologically large entry files (DoS cap)
_SUGGEST_MAX_FILES = 10000         # cap files scanned per invocation


def _safe_label(value: Any, cap: int = 40) -> str:
    """Sanitize a FREE-TEXT metadata field for safe stdout. The ledger is
    untrusted, so a poisoned field must not smuggle a payload into a
    reader's terminal. Drop ALL Unicode control (Cc) + format (Cf) chars,
    then collapse all whitespace (incl. newlines) and cap length."""
    cleaned = "".join(ch for ch in str(value or "") if unicodedata.category(ch) not in ("Cc", "Cf"))
    return " ".join(cleaned.split())[:cap]


def _entry_metadata(fm: Dict[str, Any]) -> Optional[Dict[str, str]]:
    """Return sanitized metadata for an entry, else None (drop it).

    Non-injection boundary (an entry is untrusted input; these fields print
    to stdout): DROP the entry if `pattern_key` fails PATTERN_KEY_RE or
    `type`/`priority`/`status` are not the schema enums — a bogus structured
    field signals a malformed/poisoned entry. SANITIZE the display-only `id`
    and free-text `area` rather than dropping on format."""
    iid = _safe_label(fm.get("id"), cap=64)
    pk = str(fm.get("pattern_key") or "")
    typ = str(fm.get("type") or "")
    pri = str(fm.get("priority") or "")
    status = str(fm.get("status") or "")
    # fullmatch so a returned-raw pattern_key is guaranteed to hold only
    # [a-z0-9_.] — no control/escape chars.
    if not iid or not PATTERN_KEY_RE.fullmatch(pk):
        return None
    if typ not in ENTRY_TYPES or pri not in PRIORITIES or status not in STATUSES:
        return None
    return {
        "id": iid,
        "pattern_key": pk,
        "area": _safe_label(fm.get("area"), cap=40),
        "priority": pri,
        "type": typ,
        "status": status,
    }


def _score_suggest_entry(
    meta: Dict[str, str],
    searchable: str,
    tokens: List[str],
    area_filter: Optional[str],
) -> int:
    # Rank on the SANITIZED metadata (pattern_key/area) — consistent with
    # what is filtered and displayed.
    searchable_low = searchable.lower()
    pk_low = meta["pattern_key"].lower()
    score = 0
    for tok in tokens:
        if tok in searchable_low:
            score += 1
        if tok in pk_low:
            score += 1
    if area_filter and meta["area"].lower() == area_filter.lower():
        score += 2
    return score


def _suggest_collect_hits(
    root: Path,
    *,
    area_filter: Optional[str],
    type_filter: Optional[str],
    tokens: List[str],
    filter_only: bool,
) -> List[Tuple[int, str, Dict[str, str]]]:
    """Return list of (score, id, metadata) sorted by (-score, id)."""
    entries_dir = root / "entries"
    hits: List[Tuple[int, str, Dict[str, str]]] = []
    if not entries_dir.is_dir():
        return hits

    scanned = 0
    for p in sorted(entries_dir.glob("*.md")):
        if p.name.startswith("."):
            continue
        scanned += 1
        if scanned > _SUGGEST_MAX_FILES:   # bound scan cost under a file flood
            break
        try:
            if p.stat().st_size > _SUGGEST_MAX_ENTRY_BYTES:
                continue
        except OSError:
            continue
        text = _read_text_safe(p)
        if not text:
            continue
        try:
            fm, body = parse_frontmatter(text)
        except Exception:
            continue

        meta = _entry_metadata(fm)
        if meta is None:          # schema-invalid / poisoned entry: never rank or return it
            continue

        if area_filter and meta["area"].lower() != area_filter.lower():
            continue
        if type_filter and meta["type"] != type_filter:
            continue

        searchable = _build_searchable_text(fm, body)
        score = _score_suggest_entry(meta, searchable, tokens, area_filter)
        if tokens:
            if score <= 0:
                continue
        elif not filter_only:
            continue

        hits.append((score, meta["id"], meta))

    hits.sort(key=lambda x: (-x[0], x[1]))
    return hits


def cmd_suggest(args: argparse.Namespace) -> int:
    root = _get_ledger_root(args.root)

    query_parts = [s for s in (args.query, args.error) if s and str(s).strip()]
    combined_query = " ".join(query_parts).strip()
    tokens = _tokenize_query_terms(combined_query)

    area_arg = (args.area or "").strip() or None
    type_arg = args.type

    if not tokens and not area_arg and not type_arg:
        return 0

    filter_only = not tokens and bool(area_arg or type_arg)
    hits = _suggest_collect_hits(
        root,
        area_filter=area_arg,
        type_filter=type_arg,
        tokens=tokens,
        filter_only=filter_only,
    )

    limit = max(1, int(args.limit))
    top = hits[:limit]

    if args.json:
        out = [meta for _sc, _iid, meta in top]
        print(json.dumps(out, ensure_ascii=False, indent=2))
    else:
        for _sc, _iid, meta in top:
            print(
                f"{meta['id']:<40} {meta['pattern_key']:<28} {meta['area']:<16} "
                f"{meta['priority']:<8} {meta['type']:<8} {meta['status']}"
            )
        if top:
            print(_SUGGEST_FOOTER.format(entries_dir=root / "entries"))

    return 0


# ----------------------------- main / cli -----------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="learning_ledger.py", description="Learning loop ledger tooling.")
    p.add_argument("--root", default=None, help="Ledger root dir (default: ./.learnings)")
    sub = p.add_subparsers(dest="cmd", required=True)

    add_p = sub.add_parser("add", help="Create a new ledger entry.")
    add_p.add_argument("--type", required=True, choices=list(ENTRY_TYPES.keys()))
    add_p.add_argument("--area", required=True)
    add_p.add_argument("--priority", required=True, choices=list(PRIORITIES))
    add_p.add_argument("--pattern-key", required=True, dest="pattern_key")
    add_p.add_argument("--model", default=None)
    add_p.add_argument("--effort", default=None)
    add_p.add_argument("--class", dest="klass", choices=list(CLASSES), default="mechanical",
                       help="mechanical (boundary-checkable; promotes on verified) | judgmental (heuristic; recurrence-gated)")
    add_p.add_argument("--prevention", default="",
                       help="ref to the installed guard, or 'n/a: <reason>'. Empty on a verified mechanical entry = tracked debt.")
    add_p.add_argument("--task", default=None,
                       help="external task ref (issue/PR number, ticket id, URL, or descriptive anchor) "
                            "recorded as provenance.task_ref. Omitted -> the entry is born without it "
                            "and a non-fatal advisory fires.")

    sub.add_parser("lint", help="Validate all entries and recurrences (schema + advisory injection heuristic).")
    sub.add_parser("validate", help="Alias for lint.")

    recur_p = sub.add_parser("recur", help="Record a recurrence fragment (enforces dedup + 24h lock).")
    recur_p.add_argument("pattern_key")
    recur_p.add_argument("--task", required=True)

    sub.add_parser("index", help="Regenerate INDEX.md deterministically.")
    sub.add_parser("check", help="Gate parity: lint + INDEX freshness.")

    sug_p = sub.add_parser(
        "suggest",
        help="Read-only keyword search; returns metadata only (never Fix/heal bodies).",
    )
    sug_p.add_argument("--area", default=None, help="Filter (and boost) by entry area")
    sug_p.add_argument("--error", default=None, help="Free-text search terms (alias of --query)")
    sug_p.add_argument("--query", default=None, help="Free-text search terms")
    sug_p.add_argument("--type", default=None, choices=list(ENTRY_TYPES.keys()))
    sug_p.add_argument("--limit", type=int, default=5, help="Max hits (default 5)")
    sug_p.add_argument("--json", action="store_true", help="Emit JSON list of metadata objects")

    return p


def main(argv: Optional[List[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    cmd = args.cmd

    try:
        if cmd == "add":
            return cmd_add(args)
        elif cmd in ("lint", "validate"):
            return cmd_lint(args)
        elif cmd == "recur":
            return cmd_recur(args)
        elif cmd == "index":
            return cmd_index(args)
        elif cmd == "check":
            return cmd_check(args)
        elif cmd == "suggest":
            return cmd_suggest(args)
        else:
            parser.error(f"unknown cmd {cmd}")
            return 2
    except SystemExit:
        raise
    except Exception as e:
        # never uncaught for user errors; surface cleanly
        print(f"error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
