#!/usr/bin/env python3
"""build-changelog.py — compile per-PR changelog fragments into CHANGELOG.md.

Source of truth: ``changelog.d/<id>.md`` fragment files at the repo root. The
compiler concatenates fragments in sorted order and inserts the result into the
``## [Unreleased]`` section of ``CHANGELOG.md``.

The fragment-based approach (Towncrier-style) eliminates the top-of-CHANGELOG
merge-conflict class that historically caused geometric rebase cost on deep PR
stacks (empirically: ~30 min of pure CHANGELOG conflict during the 2026-05-24
Phase 2 16-spec burst).

USAGE
  python3 scripts/build-changelog.py
      Compile fragments into CHANGELOG.md (writes the file).
  python3 scripts/build-changelog.py --check
      Compile to a temp buffer and diff against the current CHANGELOG.md.
      Exit 0 if they match, exit 1 with unified diff if they don't.
      CI uses this mode.
  python3 scripts/build-changelog.py --dry-run
      Print the compiled output to stdout without writing.

DESIGN
  * Stdlib-only.
  * Idempotent: re-running with no fragment changes produces no diff.
  * Reserved filenames (NOT treated as fragments):
      - changelog.d/README.md
      - changelog.d/.gitkeep
      - changelog.d/.skip-* (any file starting with `.skip-`)
  * Fragment ordering: lexical sort of filename. Conventional naming uses
    zero-padded incrementing IDs or PR numbers so order is intentional.
  * The compiler inserts fragments BETWEEN the ``## [Unreleased]`` line and
    the first ``###`` sub-heading (or end of section if no sub-headings).
    Existing inline entries under ``## [Unreleased]`` are PRESERVED below the
    inserted fragment block. This lets historical entries continue to live in
    CHANGELOG.md while new entries land via fragments going forward.

LIMITATIONS
  * Does NOT migrate existing inline entries. That's deliberate per the M1
    design — fragments are forward-only; existing content stays inline.
  * Does NOT handle release-time fragment archiving. That's release-changelog.py
    (planned follow-up).
"""
from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CHANGELOG_PATH = REPO_ROOT / "CHANGELOG.md"
FRAGMENTS_DIR = REPO_ROOT / "changelog.d"

UNRELEASED_HEADER = "## [Unreleased]"

# Auto-generated boundary markers — the compiler owns the content BETWEEN
# these markers and rewrites it on every build. Content outside the markers
# (inline historical entries below, file-level headers above) is preserved
# verbatim.
FRAGMENT_BLOCK_START = "<!-- changelog-fragments:start (auto-generated by build-changelog.py — do not hand-edit) -->"
FRAGMENT_BLOCK_END = "<!-- changelog-fragments:end -->"


def list_fragments() -> list[Path]:
    """Return sorted list of fragment files under changelog.d/.

    Reserved names skipped: README.md, .gitkeep, .skip-*
    """
    if not FRAGMENTS_DIR.is_dir():
        return []
    fragments: list[Path] = []
    for entry in sorted(FRAGMENTS_DIR.iterdir()):
        if not entry.is_file():
            continue
        if entry.name == "README.md":
            continue
        if entry.name == ".gitkeep":
            continue
        if entry.name.startswith(".skip-"):
            continue
        if entry.suffix != ".md":
            continue
        fragments.append(entry)
    return fragments


def read_fragments(fragments: list[Path]) -> list[str]:
    """Read each fragment's content. Trailing whitespace stripped per file."""
    return [f.read_text().rstrip() for f in fragments]


def compile_changelog(current: str, fragments_content: list[str]) -> str:
    """Insert the fragment block into CHANGELOG content under ``## [Unreleased]``.

    Replaces any existing auto-generated fragment block (delimited by the
    boundary markers) with a fresh one. If no boundary block exists, inserts
    a new one immediately after the ``## [Unreleased]`` line.
    """
    # Build the fragment block body
    if fragments_content:
        block_body = "\n\n".join(fragments_content)
        block = (
            f"\n{FRAGMENT_BLOCK_START}\n\n"
            f"{block_body}\n\n"
            f"{FRAGMENT_BLOCK_END}\n"
        )
    else:
        # No fragments: emit an empty block so the markers persist for
        # future fragments. Idempotent across "no fragments" runs.
        block = f"\n{FRAGMENT_BLOCK_START}\n{FRAGMENT_BLOCK_END}\n"

    # Strategy:
    # 1. If existing boundary block present: replace it with fresh block.
    # 2. Else: insert fresh block immediately after the ## [Unreleased] line.
    existing_block_re = re.compile(
        r"^" + re.escape(FRAGMENT_BLOCK_START) + r".*?^" + re.escape(FRAGMENT_BLOCK_END) + r"\n?",
        re.DOTALL | re.MULTILINE,
    )
    if existing_block_re.search(current):
        return existing_block_re.sub(block.lstrip("\n"), current)

    unreleased_line_re = re.compile(
        r"^(" + re.escape(UNRELEASED_HEADER) + r")\s*$", re.MULTILINE
    )
    match = unreleased_line_re.search(current)
    if not match:
        raise ValueError(
            f"CHANGELOG.md does not contain a {UNRELEASED_HEADER!r} line — "
            "add one before running the compiler."
        )
    # Insert block right after the [Unreleased] header line
    return current[: match.end()] + block + current[match.end():]


def diff_strings(a: str, b: str, fromfile: str, tofile: str) -> str:
    """Return a unified diff string between two strings."""
    a_lines = a.splitlines(keepends=True)
    b_lines = b.splitlines(keepends=True)
    return "".join(
        difflib.unified_diff(a_lines, b_lines, fromfile=fromfile, tofile=tofile)
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="diff-only mode; exit 1 if CHANGELOG.md differs from compiled output",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print compiled CHANGELOG.md to stdout without writing",
    )
    args = parser.parse_args()

    if not CHANGELOG_PATH.exists():
        print(f"ERROR: {CHANGELOG_PATH} does not exist", file=sys.stderr)
        return 2

    current = CHANGELOG_PATH.read_text()
    fragments = list_fragments()
    fragments_content = read_fragments(fragments)

    try:
        compiled = compile_changelog(current, fragments_content)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    if args.dry_run:
        sys.stdout.write(compiled)
        return 0

    if args.check:
        if current == compiled:
            print(
                f"OK: CHANGELOG.md matches compiled output "
                f"({len(fragments)} fragment(s))."
            )
            return 0
        diff = diff_strings(
            current,
            compiled,
            fromfile="CHANGELOG.md (current)",
            tofile="CHANGELOG.md (compiled from fragments)",
        )
        sys.stdout.write(diff)
        print(
            "\nERROR: CHANGELOG.md does not match compiled fragments. "
            "Run `python3 scripts/build-changelog.py` to regenerate.",
            file=sys.stderr,
        )
        return 1

    if current == compiled:
        print(
            f"OK: CHANGELOG.md already current "
            f"({len(fragments)} fragment(s); nothing to write)."
        )
        return 0

    CHANGELOG_PATH.write_text(compiled)
    print(
        f"OK: CHANGELOG.md updated "
        f"({len(fragments)} fragment(s) compiled into [Unreleased] block)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
