#!/usr/bin/env python3
"""Tests for extract_changelog_section.py (release-notes-from-changelog)."""

from __future__ import annotations

import subprocess
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from extract_changelog_section import extract_section

SAMPLE = """# Changelog — agent-collab

## [Unreleased]

<!-- changelog-fragments:start (auto-generated by build-changelog.py — do not hand-edit) -->

### Changed

- An unreleased tooling entry.

### agent-collab 6.1.1 — 2026-08-19

#### Changed

- Runtime advanced with dual-architecture artifacts.

#### Added

- macOS x86_64 (Intel) runtime artifact.

### agent-collab 6.1.0 — titled release without date

- Skills content.

<!-- changelog-fragments:end -->

## [6.0.6] — earlier compiled block

### agent-collab 6.1.1

- HISTORICAL duplicate that must never win.
"""


class ExtractSectionTests(unittest.TestCase):
    def test_extracts_full_section_first_match_wins(self) -> None:
        section = extract_section(SAMPLE, "6.1.1")
        self.assertTrue(section.startswith("### agent-collab 6.1.1 — 2026-08-19"))
        self.assertIn("macOS x86_64 (Intel) runtime artifact.", section)
        self.assertNotIn("HISTORICAL duplicate", section)
        self.assertNotIn("6.1.0", section.split("### agent-collab", 2)[-1])

    def test_stops_at_next_version_heading(self) -> None:
        section = extract_section(SAMPLE, "6.1.1")
        self.assertNotIn("Skills content", section)

    def test_titled_heading_without_date_extracts(self) -> None:
        section = extract_section(SAMPLE, "6.1.0")
        self.assertIn("Skills content.", section)
        self.assertNotIn("changelog-fragments:end", section)

    def test_exact_version_boundary(self) -> None:
        with self.assertRaises(ValueError):
            extract_section(SAMPLE.replace("6.1.1", "6.1.10"), "6.1.1")

    def test_missing_version_fails_closed(self) -> None:
        with self.assertRaises(ValueError):
            extract_section(SAMPLE, "9.9.9")

    def test_empty_section_fails_closed(self) -> None:
        text = "### agent-collab 1.0.0 — 2026-01-01\n\n### agent-collab 0.9.9\n\n- x\n"
        with self.assertRaises(ValueError):
            extract_section(text, "1.0.0")

    def test_invalid_version_rejected(self) -> None:
        with self.assertRaises(ValueError):
            extract_section(SAMPLE, "v6.1.1")

    def test_cli_against_real_repository_changelog(self) -> None:
        """The shipped CHANGELOG.md must yield the real 6.1.1 section via the CLI."""
        root = Path(__file__).resolve().parents[1]
        result = subprocess.run(
            [sys.executable, str(root / "scripts" / "extract_changelog_section.py"), "6.1.1"],
            capture_output=True,
            text=True,
            timeout=60,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("macOS x86_64 (Intel) runtime artifact", result.stdout)

    def test_cli_missing_version_exits_nonzero(self) -> None:
        root = Path(__file__).resolve().parents[1]
        result = subprocess.run(
            [sys.executable, str(root / "scripts" / "extract_changelog_section.py"), "999.999.999"],
            capture_output=True,
            text=True,
            timeout=60,
        )
        self.assertEqual(result.returncode, 1)
        self.assertIn("no section", result.stderr)


if __name__ == "__main__":
    unittest.main()
